import {
  ChildAllergy,
  ChildCondition,
  PediatricGrowthRecord,
  Encounter,
  Appointment,
  DoctorSession,
} from '../src/types/index.js';
import { DatabaseState } from './db.js';

export function getDemoAllergies(today: string): ChildAllergy[] {
  return [
    {
      id: 'alg-1',
      childId: 'c1-1', // Aarav Kumar
      allergyType: 'MEDICINE',
      substance: 'Amoxicillin & Penicillin Group',
      reaction: 'Severe urticaria, lip swelling & facial hives',
      severity: 'SEVERE',
      status: 'ACTIVE',
      identifiedDate: '2026-05-10',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Severe allergic reaction to Augmentin oral syrup. Strict contraindication for penicillin class.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-2',
      childId: 'c2-1', // Vihaan Babu
      allergyType: 'FOOD',
      substance: 'Peanuts & Tree Nuts',
      reaction: 'Perioral redness, itchy hives and swelling',
      severity: 'MODERATE',
      status: 'ACTIVE',
      identifiedDate: '2026-02-14',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Parent carries Cetirizine syrup as precaution. Avoid peanut butter and nut confectionaries.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-3',
      childId: 'c2-1', // Vihaan Babu
      allergyType: 'MEDICINE',
      substance: 'Cotrimoxazole (Septran / Sulfa)',
      reaction: 'Maculopapular drug eruption on trunk',
      severity: 'MODERATE',
      status: 'ACTIVE',
      identifiedDate: '2026-04-18',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Rash noted after 3 days of Septran for UTI. Avoid sulfonamides.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-4',
      childId: 'c3-1', // Ananya Devi
      allergyType: 'FOOD',
      substance: 'Egg Albumin (Eggs)',
      reaction: 'Cheek erythema & abdominal cramping',
      severity: 'MILD',
      status: 'ACTIVE',
      identifiedDate: '2025-10-05',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Tolerates baked goods in small amounts; avoid raw or boiled whole eggs.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-5',
      childId: 'c1-2', // Diya Kumar (Infant)
      allergyType: 'FOOD',
      substance: "Cow's Milk Protein (CMPA)",
      reaction: 'Infantile eczema flare & curdy loose stools',
      severity: 'MODERATE',
      status: 'ACTIVE',
      identifiedDate: '2025-12-12',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Advised exclusive breastfeeding or extensively hydrolyzed infant formula.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-6',
      childId: 'c4-1', // Ishaan Kumar
      allergyType: 'MEDICINE',
      substance: 'Cefixime (Cephalosporin)',
      reaction: 'Itchy papular rash over chest',
      severity: 'MODERATE',
      status: 'ACTIVE',
      identifiedDate: '2026-03-22',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Use macrolides (Azithromycin) or aminoglycosides when antibiotic indicated.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-7',
      childId: 'c5-1', // Myra Rao
      allergyType: 'ENVIRONMENTAL',
      substance: 'Dust Mites & Pollens',
      reaction: 'Allergic rhinitis, sneezing paroxysms & eczema pruritus',
      severity: 'MILD',
      status: 'ACTIVE',
      identifiedDate: '2026-01-20',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Advised frequent washing of bedsheets in warm water and mattress covers.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-8',
      childId: 'c7-1', // Kavya
      allergyType: 'MEDICINE',
      substance: 'Ibuprofen & NSAIDs',
      reaction: 'Periorbital swelling and wheezing trigger',
      severity: 'SEVERE',
      status: 'ACTIVE',
      identifiedDate: '2026-01-30',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Strictly avoid Brufen/Ibugesic. Use Paracetamol for antipyresis.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-9',
      childId: 'c6-1', // Arjun
      allergyType: 'FOOD',
      substance: 'Fava Beans & Sulfonamides (G6PD Contraindication)',
      reaction: 'Acute hemolytic crisis, dark urine, severe pallor',
      severity: 'SEVERE',
      status: 'ACTIVE',
      identifiedDate: '2024-04-10',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'G6PD Deficiency: strictly avoid fava beans, primaquine, sulfonamides, and dapsone.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-10',
      childId: 'c8-1', // Sai
      allergyType: 'ENVIRONMENTAL',
      substance: 'House Dust & Pollen Grains',
      reaction: 'Perennial allergic rhinitis, mouth breathing & itchy eyes',
      severity: 'MODERATE',
      status: 'ACTIVE',
      identifiedDate: '2025-11-05',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Exacerbates adenoid hypertrophy. Advised HEPA air filtration and barrier pillow covers.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-11',
      childId: 'c9-1', // Tara
      allergyType: 'FOOD',
      substance: 'Lactose & Cow Milk Protein',
      reaction: 'Abdominal distension, cramps & acidic loose stools',
      severity: 'MODERATE',
      status: 'ACTIVE',
      identifiedDate: '2026-01-22',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Lactose intolerance post-viral enteritis. Use lactose-free milk or soy-based nutrition.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'alg-12',
      childId: 'c10-1', // Anika
      allergyType: 'FOOD',
      substance: 'Mustard & Egg Yolk',
      reaction: 'Perioral urticarial erythema & sneezing',
      severity: 'MILD',
      status: 'ACTIVE',
      identifiedDate: '2026-03-05',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Mild food sensitivity. Avoid mustard seasoning and raw egg yolk.',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
  ];
}

export function getDemoConditions(today: string): ChildCondition[] {
  return [
    {
      id: 'cnd-1',
      childId: 'c1-1', // Aarav Kumar
      conditionName: 'Reactive Airway Disease & Recurrent Wheeze',
      category: 'RESPIRATORY',
      status: 'RECURRING',
      firstIdentifiedDate: '2026-04-12',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Triggered by seasonal cold and viral URIs. Advised warm water sips, steam inhalation, and Levolin inhaler SOS.',
      lastReviewedDate: '2026-07-22',
      followUpRecommendation: 'Review in 3 months or upon difficulty breathing',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-2',
      childId: 'c3-1', // Ananya Devi
      conditionName: 'Mild Childhood Bronchial Asthma',
      category: 'RESPIRATORY',
      status: 'ACTIVE',
      firstIdentifiedDate: '2025-11-20',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Controlled on Salbutamol + Budesonide inhaler with pediatric spacer. Avoid exposure to mosquito coils and agarbatti smoke.',
      lastReviewedDate: '2026-06-15',
      followUpRecommendation: '6-monthly pediatric pulmonology review',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-3',
      childId: 'c2-1', // Vihaan Babu
      conditionName: 'Febrile Seizure History (Single Episode)',
      category: 'CHRONIC',
      status: 'ACTIVE',
      firstIdentifiedDate: '2025-08-14',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Single generalized tonic-clonic seizure during 103°F viral fever. Prompt antipyresis advised whenever temp > 99.5°F.',
      lastReviewedDate: '2026-05-10',
      followUpRecommendation: 'Counsel parents on fever control and emergency SOS midazolam nasal spray',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-4',
      childId: 'c4-1', // Ishaan Kumar
      conditionName: 'Allergic Rhinitis with Adenoid Hypertrophy',
      category: 'ALLERGIC',
      status: 'ACTIVE',
      firstIdentifiedDate: '2026-01-10',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Mouth breathing during sleep, snoring. Salt water nasal rinse and nasal fluticasone spray.',
      lastReviewedDate: '2026-06-20',
      followUpRecommendation: 'ENT evaluation if snoring worsens',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-5',
      childId: 'c5-1', // Myra Rao
      conditionName: 'Atopic Dermatitis (Flexural Eczema)',
      category: 'ALLERGIC',
      status: 'ACTIVE',
      firstIdentifiedDate: '2025-09-12',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Dry, pruritic patches in antecubital and popliteal fossae. Prescribed barrier moisturizer cream twice daily.',
      lastReviewedDate: '2026-07-02',
      followUpRecommendation: 'Moisturize within 3 mins of bathing',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-6',
      childId: 'c6-1', // Arjun
      conditionName: 'G6PD Deficiency (Hemolytic Risk)',
      category: 'CHRONIC',
      status: 'ACTIVE',
      firstIdentifiedDate: '2024-04-05',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Enzyme deficiency confirmed on neonatal screening. Strict avoidance list provided to parents: no fava beans, primaquine, or high-dose aspirin.',
      lastReviewedDate: '2026-03-10',
      followUpRecommendation: 'Annual complete blood count and pediatric check',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-7',
      childId: 'c7-1', // Kavya
      conditionName: 'Pediatric Growth Faltering / Low Weight',
      category: 'DEVELOPMENTAL',
      status: 'ACTIVE',
      firstIdentifiedDate: '2026-02-15',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Weight at 12.1 kg (Below 10th percentile for 4 years). Advised calorie-dense foods, ghee, ragi, and egg.',
      lastReviewedDate: '2026-08-18',
      followUpRecommendation: 'Monthly growth and dietary review',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-8',
      childId: 'c8-1', // Sai
      conditionName: 'Recurrent Acute Otitis Media',
      category: 'ALLERGIC',
      status: 'RECURRING',
      firstIdentifiedDate: '2025-10-22',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Episodes associated with swimming or viral cold. Advised keeping ear canal dry during bath.',
      lastReviewedDate: '2026-06-11',
      followUpRecommendation: 'Review if ear discharge or tugging recurs',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-9',
      childId: 'c9-1', // Tara
      conditionName: 'Recurrent Acute Gastroenteritis',
      category: 'GASTROINTESTINAL',
      status: 'RESOLVED',
      firstIdentifiedDate: '2026-01-18',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      notes: 'Episodes responded promptly to oral rehydration therapy and zinc supplementation.',
      lastReviewedDate: '2026-07-29',
      followUpRecommendation: 'Maintain hand hygiene and safe filtered drinking water',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
    {
      id: 'cnd-10',
      childId: 'c10-1', // Anika
      conditionName: 'Recurrent Wheeze & Allergic Cough',
      category: 'RESPIRATORY',
      status: 'ACTIVE',
      firstIdentifiedDate: '2026-03-01',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      notes: 'Cough worsens at night and on cool exposure. Levocetirizine and warm fluids advised.',
      lastReviewedDate: '2026-08-10',
      followUpRecommendation: 'Review in 2 months',
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 09:00:00`,
    },
  ];
}

export function getDemoGrowthRecords(today: string): PediatricGrowthRecord[] {
  return [
    // Aarav Kumar
    {
      id: 'gr-1',
      childId: 'c1-1',
      recordedDate: '2026-03-15',
      ageMonths: 44,
      heightCm: 99.0,
      weightKg: 14.8,
      pediatricBmi: 15.1,
      growthStatus: 'HEALTHY',
      interpretationText: 'Height and weight tracking normally along the 50th percentile curve.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },
    {
      id: 'gr-2',
      childId: 'c1-1',
      recordedDate: '2026-07-22',
      ageMonths: 48,
      heightCm: 102.5,
      weightKg: 15.6,
      pediatricBmi: 14.9,
      heightDeltaCm: 3.5,
      weightDeltaKg: 0.8,
      growthStatus: 'HEALTHY',
      interpretationText: 'Steady upward growth trajectory. Nutrition and activity adequate.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },
    {
      id: 'gr-3',
      childId: 'c1-1',
      recordedDate: today,
      ageMonths: 48,
      heightCm: 104.0,
      weightKg: 16.2,
      pediatricBmi: 15.0,
      heightDeltaCm: 1.5,
      weightDeltaKg: 0.6,
      growthStatus: 'HEALTHY',
      interpretationText: 'Healthy pediatric growth range. Expected height velocity maintained.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Vihaan Babu
    {
      id: 'gr-4',
      childId: 'c2-1',
      recordedDate: '2026-04-18',
      ageMonths: 39,
      heightCm: 85.5,
      weightKg: 11.5,
      pediatricBmi: 15.7,
      growthStatus: 'HEALTHY',
      interpretationText: 'Weight and height within normal pediatric boundaries.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Prashant',
    },
    {
      id: 'gr-5',
      childId: 'c2-1',
      recordedDate: today,
      ageMonths: 42,
      heightCm: 87.0,
      weightKg: 12.0,
      pediatricBmi: 15.9,
      heightDeltaCm: 1.5,
      weightDeltaKg: 0.5,
      growthStatus: 'HEALTHY',
      interpretationText: 'Linear growth velocity normal. Mild recovery post-illness.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Ananya Devi
    {
      id: 'gr-6',
      childId: 'c3-1',
      recordedDate: '2026-02-10',
      ageMonths: 51,
      heightCm: 105.0,
      weightKg: 17.2,
      pediatricBmi: 15.6,
      growthStatus: 'HEALTHY',
      interpretationText: 'Height on 65th percentile. Weight healthy.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Prashant',
    },
    {
      id: 'gr-7',
      childId: 'c3-1',
      recordedDate: today,
      ageMonths: 56,
      heightCm: 108.0,
      weightKg: 18.0,
      pediatricBmi: 15.4,
      heightDeltaCm: 3.0,
      weightDeltaKg: 0.8,
      growthStatus: 'HEALTHY',
      interpretationText: 'Growth tracking well on WHO pediatric standards.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Ishaan Kumar (Short stature evaluation - needs height boost)
    {
      id: 'gr-8',
      childId: 'c4-1',
      recordedDate: '2026-01-15',
      ageMonths: 40,
      heightCm: 87.5,
      weightKg: 13.2,
      pediatricBmi: 17.2,
      growthStatus: 'REVIEW_ADVISED',
      interpretationText: 'Height slightly below median for 4-year-old boy. Dietary calcium & vitamin D recommended.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },
    {
      id: 'gr-9',
      childId: 'c4-1',
      recordedDate: today,
      ageMonths: 48,
      heightCm: 89.5,
      weightKg: 13.9,
      pediatricBmi: 17.3,
      heightDeltaCm: 2.0,
      weightDeltaKg: 0.7,
      growthStatus: 'REVIEW_ADVISED',
      interpretationText: 'Height (89.5 cm) is below expected 103 cm for age 4. Calcium, morning sunlight & stretching advised.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Kavya (Low weight - needs improvement)
    {
      id: 'gr-10',
      childId: 'c7-1',
      recordedDate: '2026-03-20',
      ageMonths: 43,
      heightCm: 99.5,
      weightKg: 11.6,
      pediatricBmi: 11.7,
      growthStatus: 'REVIEW_ADVISED',
      interpretationText: 'Weight is below 10th percentile for 4-year-old girl. High-calorie healthy fats recommended.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },
    {
      id: 'gr-11',
      childId: 'c7-1',
      recordedDate: today,
      ageMonths: 48,
      heightCm: 101.5,
      weightKg: 12.1,
      pediatricBmi: 11.7,
      heightDeltaCm: 2.0,
      weightDeltaKg: 0.5,
      growthStatus: 'REVIEW_ADVISED',
      interpretationText: 'Weight (12.1 kg) below expected 16.1 kg. Ragi malt, ghee, boiled eggs & nut powder advised.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Diya Kumar (Infant)
    {
      id: 'gr-12',
      childId: 'c1-2',
      recordedDate: today,
      ageMonths: 10,
      heightCm: 75.0,
      weightKg: 9.6,
      pediatricBmi: 17.1,
      growthStatus: 'HEALTHY',
      interpretationText: 'Infant growth tracking appropriately on WHO 10-month standards.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Prashant',
    },

    // Myra Rao
    {
      id: 'gr-13',
      childId: 'c5-1',
      recordedDate: today,
      ageMonths: 36,
      heightCm: 95.0,
      weightKg: 14.2,
      pediatricBmi: 15.7,
      growthStatus: 'HEALTHY',
      interpretationText: 'Normal height & weight for 3-year-old toddler.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Arjun
    {
      id: 'gr-14',
      childId: 'c6-1',
      recordedDate: today,
      ageMonths: 36,
      heightCm: 96.5,
      weightKg: 15.0,
      pediatricBmi: 16.1,
      growthStatus: 'HEALTHY',
      interpretationText: 'Robust growth parameters along 60th percentile.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Sai
    {
      id: 'gr-15',
      childId: 'c8-1',
      recordedDate: today,
      ageMonths: 36,
      heightCm: 97.0,
      weightKg: 14.8,
      pediatricBmi: 15.7,
      growthStatus: 'HEALTHY',
      interpretationText: 'Healthy pediatric growth velocity.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Tara
    {
      id: 'gr-16',
      childId: 'c9-1',
      recordedDate: today,
      ageMonths: 36,
      heightCm: 94.0,
      weightKg: 13.5,
      pediatricBmi: 15.3,
      growthStatus: 'HEALTHY',
      interpretationText: 'Normal growth curve post recovery from enteritis.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Subba Rao Vadarevu',
    },

    // Anika
    {
      id: 'gr-17',
      childId: 'c10-1',
      recordedDate: today,
      ageMonths: 36,
      heightCm: 93.5,
      weightKg: 13.2,
      pediatricBmi: 15.1,
      growthStatus: 'HEALTHY',
      interpretationText: 'Healthy toddler milestone and growth indicators.',
      doctorConfirmed: true,
      recordedByRole: 'DOCTOR',
      recordedByName: 'Dr. Prashant',
    },
  ];
}

export function getDemoEncounters(today: string): Encounter[] {
  return [
    // Encounter 1: Aarav Kumar (Gastritis)
    {
      id: 'enc-1',
      appointmentId: 'apt-1',
      childId: 'c1-1',
      childPermanentId: 'DM-SDCH-000101',
      childName: 'Aarav Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-07-22',
      visitType: 'PHYSICAL_OPD',
      heightCm: 102.5,
      weightKg: 15.6,
      temperatureF: 98.6,
      pulseRate: 98,
      pediatricBmi: 14.9,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Vomiting x 3 episodes', 'Mild abdominal colic'],
      clinicalObservations: 'Abdomen soft, non-tender. Mild dehydration, alert and responsive.',
      diagnosis: 'Acute Gastritis with mild dehydration',
      doctorNotes: 'Advised oral rehydration solution (ORS), light bland diet, avoid milk products for 24h.',
      followUpDate: '2026-07-25',
      status: 'FINALIZED',
      createdAt: '2026-07-22 10:20:00',
      updatedAt: '2026-07-22 10:20:00',
      prescription: {
        id: 'rx-1',
        encounterId: 'enc-1',
        prescriptionNumber: 'RX-SDCH-2026-000084',
        childId: 'c1-1',
        childPermanentId: 'DM-SDCH-000101',
        childName: 'Aarav Kumar',
        childAge: 4,
        childGender: 'Boy',
        weightKg: 15.6,
        heightCm: 102.5,
        temperatureF: 98.6,
        pulseRate: 98,
        pediatricBmi: 14.9,
        bloodGroup: 'O+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-07-22',
        version: 1,
        diagnosis: 'Acute Gastritis with mild dehydration',
        allergyBannerSnapshot: ['Amoxicillin & Penicillin Group (Severe urticaria, lip swelling & facial hives)'],
        items: [
          {
            id: 'rxi-1',
            medicineName: 'Ondansetron Oral Solution (Emset)',
            genericName: 'Ondansetron 2mg/5ml',
            form: 'SYRUP',
            strength: '2mg/5ml',
            dosage: '3 ml',
            frequency: 'SOS',
            timing: 'BEFORE_FOOD',
            durationDays: 2,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Give 3 ml 15 minutes before food only if child vomits.',
            instructionTe: 'వాంతులు అయినప్పుడు మాత్రమే భోజనానికి 15 నిమిషాల ముందు 3 ml ఇవ్వండి.',
          },
          {
            id: 'rxi-2',
            medicineName: 'Probiotic Zinc Sachet (Darolac / Econorm)',
            genericName: 'Saccharomyces boulardii + Zinc',
            form: 'DROPS',
            strength: '250mg',
            dosage: '1 sachet',
            frequency: 'TWICE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 5,
            timeSlots: ['Morning', 'Night'],
            instructionEn: 'Mix 1 sachet in lukewarm water or breastmilk twice daily for 5 days.',
            instructionTe: 'గోరువెచ్చని నీటిలో ఒక ప్యాకెట్ కలిపి రోజుకు రెండుసార్లు 5 రోజుల పాటు ఇవ్వండి.',
          },
        ],
        specialNotesEn: 'Plentiful sips of ORS after every vomiting episode. Avoid fruit juices for 24h.',
        specialNotesTe: 'ప్రతి వాంతి తర్వాత తరచుగా ఓఆర్ఎస్ (ORS) నీరు కొద్దికొద్దిగా తాగించండి.',
        followUpDate: '2026-07-25',
        status: 'FINALIZED',
        createdAt: '2026-07-22 10:20:00',
        updatedAt: '2026-07-22 10:20:00',
      },
    },

    // Encounter 2: Aarav Kumar (Wheezing Episode - Dr. Prashant)
    {
      id: 'enc-2',
      childId: 'c1-1',
      childPermanentId: 'DM-SDCH-000101',
      childName: 'Aarav Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      date: '2026-05-10',
      visitType: 'PHYSICAL_OPD',
      heightCm: 101.0,
      weightKg: 15.2,
      temperatureF: 99.2,
      pulseRate: 104,
      pediatricBmi: 14.9,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Nocturnal dry cough', 'Mild expiratory wheeze'],
      clinicalObservations: 'Bilateral scattered rhonchi, air entry good. No subcostal retractions.',
      diagnosis: 'Viral Bronchospasm & Reactive Airway Episode',
      doctorNotes: 'Prescribed Levolin and Budecort via spacer. Avoid night exposure to cool air.',
      followUpDate: '2026-05-15',
      status: 'FINALIZED',
      createdAt: '2026-05-10 11:30:00',
      updatedAt: '2026-05-10 11:30:00',
      prescription: {
        id: 'rx-2',
        encounterId: 'enc-2',
        prescriptionNumber: 'RX-SDCH-2026-000042',
        childId: 'c1-1',
        childPermanentId: 'DM-SDCH-000101',
        childName: 'Aarav Kumar',
        childAge: 4,
        childGender: 'Boy',
        weightKg: 15.2,
        heightCm: 101.0,
        temperatureF: 99.2,
        pulseRate: 104,
        pediatricBmi: 14.9,
        bloodGroup: 'O+',
        doctorId: 'dr-prashant',
        doctorName: 'Dr. Prashant',
        doctorRegNo: 'APMC-45120',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-05-10',
        version: 1,
        diagnosis: 'Viral Bronchospasm & Reactive Airway Episode',
        allergyBannerSnapshot: ['Amoxicillin & Penicillin Group (Severe urticaria, lip swelling & facial hives)'],
        items: [
          {
            id: 'rxi-3',
            medicineName: 'Levosalbutamol Inhaler (Levolin 50mcg)',
            genericName: 'Levosalbutamol 50mcg',
            form: 'INHALER',
            strength: '50mcg/puff',
            dosage: '2 puffs',
            frequency: 'THRICE_DAILY',
            timing: 'BEFORE_FOOD',
            durationDays: 5,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: '2 puffs with baby mask spacer thrice daily for 5 days.',
            instructionTe: 'బేబీ మాస్క్ స్పేసర్ ద్వారా రోజుకు 3 సార్లు 2 పఫ్స్ ఇవ్వండి.',
          },
          {
            id: 'rxi-4',
            medicineName: 'Budesonide Respules 0.5mg (Budecort)',
            genericName: 'Budesonide 0.5mg/2ml',
            form: 'DROPS',
            strength: '0.5mg/2ml',
            dosage: '1 respule',
            frequency: 'TWICE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 3,
            timeSlots: ['Morning', 'Night'],
            instructionEn: 'Nebulize with 2 ml normal saline twice daily for 3 days.',
            instructionTe: 'రోజుకు రెండుసార్లు నెబ్యులైజర్ ద్వారా 3 రోజుల పాటు ఆవిరి పట్టించండి.',
          },
        ],
        specialNotesEn: 'Steam inhalation twice daily. Rinse mouth with water after inhaler.',
        specialNotesTe: 'ఇన్హేలర్ వాడిన తర్వాత శుభ్రమైన నీటితో నోరు పుక్కిలించి ఉమ్మివేయించండి.',
        followUpDate: '2026-05-15',
        status: 'FINALIZED',
        createdAt: '2026-05-10 11:30:00',
        updatedAt: '2026-05-10 11:30:00',
      },
    },

    // Encounter 3: Vihaan Babu (Acute Bronchitis & Wheeze)
    {
      id: 'enc-3',
      appointmentId: 'apt-2',
      childId: 'c2-1',
      childPermanentId: 'DM-SDCH-000103',
      childName: 'Vihaan Babu',
      parentId: 'p2',
      parentName: 'Suresh Babu',
      parentMobile: '9000000002',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-08-04',
      visitType: 'PHYSICAL_OPD',
      heightCm: 86.5,
      weightKg: 11.8,
      temperatureF: 100.4,
      pulseRate: 112,
      pediatricBmi: 15.8,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Barking cough x 4 days', 'Fever spike 100.4°F'],
      clinicalObservations: 'Chest bilateral coarse rhonchi. Throat congested. Pharynx erythematous.',
      diagnosis: 'Acute Asthmatic Bronchitis & Viral Pharyngitis',
      doctorNotes: 'Sulfa and Peanuts allergy noted. Treated safely with Montelukast and Levosalbutamol.',
      followUpDate: '2026-08-08',
      status: 'FINALIZED',
      createdAt: '2026-08-04 10:45:00',
      updatedAt: '2026-08-04 10:45:00',
      prescription: {
        id: 'rx-3',
        encounterId: 'enc-3',
        prescriptionNumber: 'RX-SDCH-2026-000112',
        childId: 'c2-1',
        childPermanentId: 'DM-SDCH-000103',
        childName: 'Vihaan Babu',
        childAge: 3,
        childGender: 'Boy',
        weightKg: 11.8,
        heightCm: 86.5,
        temperatureF: 100.4,
        pulseRate: 112,
        pediatricBmi: 15.8,
        bloodGroup: 'A+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-08-04',
        version: 1,
        diagnosis: 'Acute Asthmatic Bronchitis & Viral Pharyngitis',
        allergyBannerSnapshot: [
          'Peanuts & Tree Nuts (Perioral redness, itchy hives and swelling)',
          'Cotrimoxazole (Septran / Sulfa) (Maculopapular drug eruption on trunk)',
        ],
        items: [
          {
            id: 'rxi-5',
            medicineName: 'Montelukast + Levocetirizine Syrup (Monticope)',
            genericName: 'Montelukast 4mg + Levocetirizine 2.5mg/5ml',
            form: 'SYRUP',
            strength: '5ml',
            dosage: '5 ml',
            frequency: 'ONCE_DAILY',
            timing: 'AT_BEDTIME',
            durationDays: 7,
            timeSlots: ['Night'],
            instructionEn: 'Give 5 ml once daily at night for 7 days.',
            instructionTe: 'రాత్రి పడుకునే ముందు 5 ml సిరప్ రోజుకు ఒకసారి 7 రోజుల పాటు ఇవ్వండి.',
          },
          {
            id: 'rxi-6',
            medicineName: 'Paracetamol Pediatric Oral Suspension (Crocin 120)',
            genericName: 'Paracetamol 120mg/5ml',
            form: 'SYRUP',
            strength: '120mg/5ml',
            dosage: '7 ml',
            frequency: 'SOS',
            timing: 'AFTER_FOOD',
            durationDays: 3,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Give 7 ml only when fever exceeds 99.5°F (min 6 hrs gap).',
            instructionTe: 'జ్వరం 99.5°F కంటే ఎక్కువ ఉన్నప్పుడు మాత్రమే 7 ml ఇవ్వండి (కనీసం 6 గంటల వ్యవధి).',
          },
        ],
        specialNotesEn: 'Keep child well hydrated. Warm water sips and saline nasal drops.',
        specialNotesTe: 'వెచ్చని నీరు తాగించండి. చల్లటి గాలి మరియు ఐస్ క్రీములు ఇవ్వవద్దు.',
        followUpDate: '2026-08-08',
        status: 'FINALIZED',
        createdAt: '2026-08-04 10:45:00',
        updatedAt: '2026-08-04 10:45:00',
      },
    },

    // Encounter 4: Ananya Devi (Asthma Exacerbation)
    {
      id: 'enc-4',
      appointmentId: 'apt-3',
      childId: 'c3-1',
      childPermanentId: 'DM-SDCH-000104',
      childName: 'Ananya Devi',
      parentId: 'p3',
      parentName: 'Lakshmi Devi',
      parentMobile: '9000000003',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-07-15',
      visitType: 'PHYSICAL_OPD',
      heightCm: 107.5,
      weightKg: 17.8,
      temperatureF: 98.4,
      pulseRate: 96,
      pediatricBmi: 15.4,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Recurrent wheeze & breathlessness post dust exposure'],
      clinicalObservations: 'Chest bilaterally clear post nebulization in clinic. SpO2 99% on room air.',
      diagnosis: 'Acute Asthma Exacerbation - Controlled',
      doctorNotes: 'Advised continuing Budesonide inhaler for 1 month as maintenance.',
      followUpDate: '2026-07-29',
      status: 'FINALIZED',
      createdAt: '2026-07-15 11:10:00',
      updatedAt: '2026-07-15 11:10:00',
      prescription: {
        id: 'rx-4',
        encounterId: 'enc-4',
        prescriptionNumber: 'RX-SDCH-2026-000098',
        childId: 'c3-1',
        childPermanentId: 'DM-SDCH-000104',
        childName: 'Ananya Devi',
        childAge: 4,
        childGender: 'Girl',
        weightKg: 17.8,
        heightCm: 107.5,
        temperatureF: 98.4,
        pulseRate: 96,
        pediatricBmi: 15.4,
        bloodGroup: 'AB+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-07-15',
        version: 1,
        diagnosis: 'Acute Asthma Exacerbation - Controlled',
        allergyBannerSnapshot: ['Egg Albumin (Eggs) (Cheek erythema & abdominal cramping)'],
        items: [
          {
            id: 'rxi-7',
            medicineName: 'Salbutamol Inhaler (Asthalin 100mcg)',
            genericName: 'Salbutamol 100mcg',
            form: 'INHALER',
            strength: '100mcg/puff',
            dosage: '2 puffs',
            frequency: 'SOS',
            timing: 'BEFORE_FOOD',
            durationDays: 7,
            timeSlots: ['Morning', 'Night'],
            instructionEn: '2 puffs via spacer only if breathlessness or coughing occurs.',
            instructionTe: 'దగ్గు లేదా ఆయాసం వచ్చినప్పుడు మాత్రమే స్పేసర్ ద్వారా 2 పఫ్స్ ఇవ్వండి.',
          },
          {
            id: 'rxi-8',
            medicineName: 'Budesonide Inhaler (Budecort 100mcg)',
            genericName: 'Budesonide 100mcg',
            form: 'INHALER',
            strength: '100mcg/puff',
            dosage: '1 puff',
            frequency: 'TWICE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 30,
            timeSlots: ['Morning', 'Night'],
            instructionEn: '1 puff regular maintenance twice daily for 1 month.',
            instructionTe: 'స్పేసర్ ద్వారా ఉదయం 1 పఫ్, రాత్రి 1 పఫ్ నెల రోజుల పాటు క్రమం తప్పకుండా ఇవ్వండి.',
          },
        ],
        specialNotesEn: 'Clean spacer with mild soapy water weekly. Air dry naturally.',
        specialNotesTe: 'స్పేసర్‌ను వారానికి ఒకసారి గోరువెచ్చని సబ్బు నీటితో కడిగి ఆరబెట్టండి.',
        followUpDate: '2026-07-29',
        status: 'FINALIZED',
        createdAt: '2026-07-15 11:10:00',
        updatedAt: '2026-07-15 11:10:00',
      },
    },

    // Encounter 5: Ishaan Kumar (Viral Pharyngitis & Growth Review)
    {
      id: 'enc-5',
      appointmentId: 'apt-4',
      childId: 'c4-1',
      childPermanentId: 'DM-SDCH-000106',
      childName: 'Ishaan Kumar',
      parentId: 'p4',
      parentName: 'Rajesh Kumar',
      parentMobile: '9000000004',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-06-20',
      visitType: 'PHYSICAL_OPD',
      heightCm: 88.8,
      weightKg: 13.5,
      temperatureF: 99.8,
      pulseRate: 102,
      pediatricBmi: 17.1,
      growthStatus: 'REVIEW_ADVISED',
      chiefComplaints: ['Sore throat', 'Mild fever', 'Parent concerned about low height'],
      clinicalObservations: 'Throat congested, no tonsillar exudates. Height 88.8 cm (Requires height guidance).',
      diagnosis: 'Viral Upper Respiratory Infection & Pediatric Stature Review',
      doctorNotes: 'Cefixime allergy documented. Prescribed safe symptomatic care and Vitamin D3.',
      followUpDate: '2026-06-25',
      status: 'FINALIZED',
      createdAt: '2026-06-20 11:20:00',
      updatedAt: '2026-06-20 11:20:00',
      prescription: {
        id: 'rx-5',
        encounterId: 'enc-5',
        prescriptionNumber: 'RX-SDCH-2026-000067',
        childId: 'c4-1',
        childPermanentId: 'DM-SDCH-000106',
        childName: 'Ishaan Kumar',
        childAge: 4,
        childGender: 'Boy',
        weightKg: 13.5,
        heightCm: 88.8,
        temperatureF: 99.8,
        pulseRate: 102,
        pediatricBmi: 17.1,
        bloodGroup: 'B+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-06-20',
        version: 1,
        diagnosis: 'Viral Upper Respiratory Infection & Pediatric Stature Review',
        allergyBannerSnapshot: ['Cefixime (Cephalosporin) (Itchy papular rash over chest)'],
        items: [
          {
            id: 'rxi-9',
            medicineName: 'Paracetamol Oral Suspension (Calpol 250)',
            genericName: 'Paracetamol 250mg/5ml',
            form: 'SYRUP',
            strength: '250mg/5ml',
            dosage: '4 ml',
            frequency: 'SOS',
            timing: 'AFTER_FOOD',
            durationDays: 3,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: '4 ml only if fever > 99.5°F or throat pain is bothersome.',
            instructionTe: 'జ్వరం లేదా గొంతు నొప్పి ఉన్నప్పుడు మాత్రమే 4 ml ఇవ్వండి.',
          },
          {
            id: 'rxi-10',
            medicineName: 'Vitamin D3 Drops (D3 Must 400 IU)',
            genericName: 'Cholecalciferol 400 IU/ml',
            form: 'DROPS',
            strength: '400 IU/ml',
            dosage: '1 ml',
            frequency: 'ONCE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 30,
            timeSlots: ['Morning'],
            instructionEn: '1 ml once daily after breakfast for height and bone health.',
            instructionTe: 'ఉదయం అల్పాహారం తర్వాత 1 ml చుక్కల మందు రోజుకు ఒకసారి ఇవ్వండి.',
          },
        ],
        specialNotesEn: '2 glasses of milk daily. Morning sun exposure 15-20 mins for growth.',
        specialNotesTe: 'ఎముకల బలం మరియు ఎత్తు పెరగడానికి రోజుకు 2 గ్లాసుల పాలు మరియు ఉదయపు ఎండ తగిలేలా చూడండి.',
        followUpDate: '2026-06-25',
        status: 'FINALIZED',
        createdAt: '2026-06-20 11:20:00',
        updatedAt: '2026-06-20 11:20:00',
      },
    },

    // Encounter 6: Myra Rao (Atopic Dermatitis)
    {
      id: 'enc-6',
      appointmentId: 'apt-5',
      childId: 'c5-1',
      childPermanentId: 'DM-SDCH-000107',
      childName: 'Myra Rao',
      parentId: 'p5',
      parentName: 'Priya Rao',
      parentMobile: '9000000005',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-07-02',
      visitType: 'PHYSICAL_OPD',
      heightCm: 94.5,
      weightKg: 14.0,
      temperatureF: 98.4,
      pulseRate: 98,
      pediatricBmi: 15.7,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Pruritic dry rash behind knees and elbow creases'],
      clinicalObservations: 'Erythematous excoriated plaques on flexural aspects. Dry xerotic skin.',
      diagnosis: 'Flexural Atopic Dermatitis Flare',
      doctorNotes: 'Prescribed mild topical steroid for 5 days followed by intensive barrier moisturization.',
      followUpDate: '2026-07-16',
      status: 'FINALIZED',
      createdAt: '2026-07-02 11:40:00',
      updatedAt: '2026-07-02 11:40:00',
      prescription: {
        id: 'rx-6',
        encounterId: 'enc-6',
        prescriptionNumber: 'RX-SDCH-2026-000078',
        childId: 'c5-1',
        childPermanentId: 'DM-SDCH-000107',
        childName: 'Myra Rao',
        childAge: 3,
        childGender: 'Girl',
        weightKg: 14.0,
        heightCm: 94.5,
        temperatureF: 98.4,
        pulseRate: 98,
        pediatricBmi: 15.7,
        bloodGroup: 'A-',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-07-02',
        version: 1,
        diagnosis: 'Flexural Atopic Dermatitis Flare',
        allergyBannerSnapshot: ['Dust Mites & Pollens (Allergic rhinitis, sneezing paroxysms & eczema pruritus)'],
        items: [
          {
            id: 'rxi-11',
            medicineName: 'Hydrocortisone 1% Cream',
            genericName: 'Hydrocortisone acetate 1%',
            form: 'CREAM',
            strength: '1%',
            dosage: 'Thin layer',
            frequency: 'TWICE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 5,
            timeSlots: ['Morning', 'Night'],
            instructionEn: 'Apply a very thin layer gently on red itchy patches twice daily for 5 days only.',
            instructionTe: 'ఎర్రటి దురద ఉన్న భాగాలపై రోజుకు రెండుసార్లు మాత్రమే పలుచగా రాయండి (5 రోజులు మాత్రమే).',
          },
          {
            id: 'rxi-12',
            medicineName: 'Cetaphil Restoraderm Moisturizing Wash & Lotion',
            genericName: 'Ceramide Barrier Complex',
            form: 'CREAM',
            strength: 'Ceramide',
            dosage: 'Liberal application',
            frequency: 'THRICE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 30,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Apply generously all over body within 3 minutes of bathing and throughout day.',
            instructionTe: 'స్నానం చేసిన 3 నిమిషాల్లోపు ఒంటి నిండా మాయిశ్చరైజర్ రాయండి.',
          },
        ],
        specialNotesEn: 'Use mild syndet cleanser. Avoid hot water baths.',
        specialNotesTe: 'గోరువెచ్చని నీటితో మాత్రమే స్నానం చేయించండి. వేడి నీరు వాడవద్దు.',
        followUpDate: '2026-07-16',
        status: 'FINALIZED',
        createdAt: '2026-07-02 11:40:00',
        updatedAt: '2026-07-02 11:40:00',
      },
    },

    // Encounter 7: Arjun (G6PD Deficiency URI)
    {
      id: 'enc-7',
      appointmentId: 'apt-6',
      childId: 'c6-1',
      childPermanentId: 'DM-SDCH-000109',
      childName: 'Arjun',
      parentId: 'p6',
      parentName: 'Mahesh',
      parentMobile: '9000000006',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      date: '2026-04-12',
      visitType: 'PHYSICAL_OPD',
      heightCm: 95.0,
      weightKg: 14.5,
      temperatureF: 100.2,
      pulseRate: 108,
      pediatricBmi: 16.1,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Runny nose', 'Low grade fever', 'Sneezing'],
      clinicalObservations: 'No pallor, no icterus. Throat mildly injected. Alert and playing.',
      diagnosis: 'Acute Viral Rhinopharyngitis (G6PD Safe Protocol)',
      doctorNotes: 'G6PD deficiency alert checked. Avoided all oxidant drugs and sulfonamides.',
      followUpDate: '2026-04-16',
      status: 'FINALIZED',
      createdAt: '2026-04-12 10:30:00',
      updatedAt: '2026-04-12 10:30:00',
      prescription: {
        id: 'rx-7',
        encounterId: 'enc-7',
        prescriptionNumber: 'RX-SDCH-2026-000035',
        childId: 'c6-1',
        childPermanentId: 'DM-SDCH-000109',
        childName: 'Arjun',
        childAge: 3,
        childGender: 'Boy',
        weightKg: 14.5,
        heightCm: 95.0,
        temperatureF: 100.2,
        pulseRate: 108,
        pediatricBmi: 16.1,
        bloodGroup: 'B+',
        doctorId: 'dr-prashant',
        doctorName: 'Dr. Prashant',
        doctorRegNo: 'APMC-45120',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-04-12',
        version: 1,
        diagnosis: 'Acute Viral Rhinopharyngitis (G6PD Safe Protocol)',
        allergyBannerSnapshot: ['G6PD Deficiency: Contraindicated with Sulfonamides, Dapsone, Nitrofurantoin'],
        items: [
          {
            id: 'rxi-13',
            medicineName: 'Paracetamol Pediatric Syrup (Crocin 120)',
            genericName: 'Paracetamol 120mg/5ml',
            form: 'SYRUP',
            strength: '120mg/5ml',
            dosage: '7 ml',
            frequency: 'SOS',
            timing: 'AFTER_FOOD',
            durationDays: 3,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Give 7 ml only when temp exceeds 99.5°F. G6PD safe antipyretic.',
            instructionTe: 'జ్వరం ఉన్నప్పుడు మాత్రమే 7 ml ఇవ్వండి (G6PD కి సురక్షితమైన మందు).',
          },
          {
            id: 'rxi-14',
            medicineName: 'Saline Nasal Drops (Otrivin S)',
            genericName: 'Sodium Chloride 0.9%',
            form: 'DROPS',
            strength: '0.9%',
            dosage: '2 drops',
            frequency: 'THRICE_DAILY',
            timing: 'BEFORE_FOOD',
            durationDays: 5,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Instill 2 drops in each nostril before feedings or sleep.',
            instructionTe: 'రెండు ముక్కు రంధ్రాలలో 2 చుక్కల చొప్పున వేయండి.',
          },
        ],
        specialNotesEn: 'Ensure high fluid intake. Avoid mothballs and fava beans.',
        specialNotesTe: 'పిల్లలకు కొబ్బరినీళ్లు, పండ్ల రసాలు తాగించండి. రసాయన వాసనలు తగలకుండా చూడండి.',
        followUpDate: '2026-04-16',
        status: 'FINALIZED',
        createdAt: '2026-04-12 10:30:00',
        updatedAt: '2026-04-12 10:30:00',
      },
    },

    // Encounter 8: Kavya (Low Weight / Tonsillitis)
    {
      id: 'enc-8',
      appointmentId: 'apt-7',
      childId: 'c7-1',
      childPermanentId: 'DM-SDCH-000110',
      childName: 'Kavya',
      parentId: 'p7',
      parentName: 'Sravani',
      parentMobile: '9000000007',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-08-18',
      visitType: 'PHYSICAL_OPD',
      heightCm: 101.0,
      weightKg: 12.0,
      temperatureF: 101.0,
      pulseRate: 110,
      pediatricBmi: 11.8,
      growthStatus: 'REVIEW_ADVISED',
      chiefComplaints: ['Throat pain on swallowing', 'High fever 101°F', 'Poor appetite'],
      clinicalObservations: 'Bilateral tonsils Grade 2 enlarged with follicular exudates. Submandibular lymphadenopathy.',
      diagnosis: 'Acute Follicular Tonsillitis & Pediatric Growth Faltering',
      doctorNotes: 'Severe NSAID allergy noted. Prescribed Azithromycin and high-calorie nutritional guidance.',
      followUpDate: '2026-08-22',
      status: 'FINALIZED',
      createdAt: '2026-08-18 11:50:00',
      updatedAt: '2026-08-18 11:50:00',
      prescription: {
        id: 'rx-8',
        encounterId: 'enc-8',
        prescriptionNumber: 'RX-SDCH-2026-000129',
        childId: 'c7-1',
        childPermanentId: 'DM-SDCH-000110',
        childName: 'Kavya',
        childAge: 4,
        childGender: 'Girl',
        weightKg: 12.0,
        heightCm: 101.0,
        temperatureF: 101.0,
        pulseRate: 110,
        pediatricBmi: 11.8,
        bloodGroup: 'O+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-08-18',
        version: 1,
        diagnosis: 'Acute Follicular Tonsillitis & Pediatric Growth Faltering',
        allergyBannerSnapshot: ['Ibuprofen & NSAIDs (Periorbital swelling and wheezing trigger - STRIKE CONTRAINDICATION)'],
        items: [
          {
            id: 'rxi-15',
            medicineName: 'Azithromycin Pediatric Suspension (Azee 100)',
            genericName: 'Azithromycin 100mg/5ml',
            form: 'SYRUP',
            strength: '100mg/5ml',
            dosage: '5 ml',
            frequency: 'ONCE_DAILY',
            timing: 'BEFORE_FOOD',
            durationDays: 3,
            timeSlots: ['Morning'],
            instructionEn: 'Give 5 ml once daily 1 hour before food for 3 consecutive days only.',
            instructionTe: 'ఆహారానికి 1 గంట ముందు ఉదయం 5 ml రోజుకు ఒకసారి 3 రోజులు మాత్రమే ఇవ్వండి.',
          },
          {
            id: 'rxi-16',
            medicineName: 'Paracetamol Suspension (Crocin 120)',
            genericName: 'Paracetamol 120mg/5ml',
            form: 'SYRUP',
            strength: '120mg/5ml',
            dosage: '6 ml',
            frequency: 'SOS',
            timing: 'AFTER_FOOD',
            durationDays: 3,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Give 6 ml for fever or throat pain (DO NOT use Brufen/Ibuprofen).',
            instructionTe: 'జ్వరం లేదా గొంతు నొప్పి ఉన్నప్పుడు 6 ml ఇవ్వండి (బ్రూఫెన్ వాడవద్దు).',
          },
        ],
        specialNotesEn: 'Warm salt water gargles. High calorie ragi porridge and egg for weight improvement.',
        specialNotesTe: 'బరువు పెరగడానికి ఉడకబెట్టిన గుడ్డు, రాగి జావ మరియు నెయ్యితో కూడిన ఆహారం ఇవ్వండి.',
        followUpDate: '2026-08-22',
        status: 'FINALIZED',
        createdAt: '2026-08-18 11:50:00',
        updatedAt: '2026-08-18 11:50:00',
      },
    },

    // Encounter 9: Diya Kumar (Infant CMPA & Weaning - Dr. Prashant)
    {
      id: 'enc-9',
      appointmentId: 'apt-p1',
      childId: 'c1-2',
      childPermanentId: 'DM-SDCH-000102',
      childName: 'Diya Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      date: '2026-06-05',
      visitType: 'PHYSICAL_OPD',
      heightCm: 72.5,
      weightKg: 8.9,
      temperatureF: 98.6,
      pulseRate: 116,
      pediatricBmi: 16.9,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Curdy loose stools post formula feed', 'Mild abdominal colic'],
      clinicalObservations: 'Infant alert, hydrated. Abdomen soft. Mild perianal erythema.',
      diagnosis: "Cow's Milk Protein Allergy (CMPA) & Weaning Review",
      doctorNotes: 'Advised switching to extensively hydrolyzed infant formula. Start ragi and boiled mashed apple.',
      followUpDate: '2026-07-05',
      status: 'FINALIZED',
      createdAt: '2026-06-05 10:15:00',
      updatedAt: '2026-06-05 10:15:00',
      prescription: {
        id: 'rx-9',
        encounterId: 'enc-9',
        prescriptionNumber: 'RX-SDCH-2026-000054',
        childId: 'c1-2',
        childPermanentId: 'DM-SDCH-000102',
        childName: 'Diya Kumar',
        childAge: 1,
        childGender: 'Girl',
        weightKg: 8.9,
        heightCm: 72.5,
        temperatureF: 98.6,
        pulseRate: 116,
        pediatricBmi: 16.9,
        bloodGroup: 'B+',
        doctorId: 'dr-prashant',
        doctorName: 'Dr. Prashant',
        doctorRegNo: 'APMC-45120',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-06-05',
        version: 1,
        diagnosis: "Cow's Milk Protein Allergy (CMPA) & Weaning Review",
        allergyBannerSnapshot: ["Cow's Milk Protein (CMPA) (Infantile eczema flare & curdy loose stools)"],
        items: [
          {
            id: 'rxi-17',
            medicineName: 'Zinc Oral Drops (Zinconia)',
            genericName: 'Zinc gluconate 20mg/ml',
            form: 'DROPS',
            strength: '20mg/ml',
            dosage: '0.5 ml',
            frequency: 'ONCE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 14,
            timeSlots: ['Morning'],
            instructionEn: 'Give 0.5 ml once daily for gut mucosa healing for 14 days.',
            instructionTe: 'ఉదయం ఆహారం తర్వాత 0.5 ml చుక్కల మందు 14 రోజుల పాటు ఇవ్వండి.',
          },
          {
            id: 'rxi-18',
            medicineName: 'Probiotic Infant Drops (Enterogermina / Darolac)',
            genericName: 'Bacillus clausii spores',
            form: 'DROPS',
            strength: '2 billion spores',
            dosage: '1 mini bottle',
            frequency: 'ONCE_DAILY',
            timing: 'BEFORE_FOOD',
            durationDays: 5,
            timeSlots: ['Morning'],
            instructionEn: 'Give 1 mini bottle orally once daily for 5 days.',
            instructionTe: 'రోజుకు ఒక చిన్న సీసా మందు ఉదయం తాగించండి.',
          },
        ],
        specialNotesEn: 'Strict avoidance of dairy milk products. Introduce cooked ragi and dal water.',
        specialNotesTe: 'ఆవు పాలు మరియు డెయిరీ పదార్థాలు ఇవ్వవద్దు. ఉడికించిన రాగి జావ, పప్పు నీరు ఇవ్వండి.',
        followUpDate: '2026-07-05',
        status: 'FINALIZED',
        createdAt: '2026-06-05 10:15:00',
        updatedAt: '2026-06-05 10:15:00',
      },
    },

    // Encounter 10: Sai (Acute Otitis Media & Adenoid Hypertrophy)
    {
      id: 'enc-10',
      appointmentId: 'apt-8',
      childId: 'c8-1',
      childPermanentId: 'DM-SDCH-000112',
      childName: 'Sai',
      parentId: 'p8',
      parentName: 'Venkatesh',
      parentMobile: '9000000008',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-06-11',
      visitType: 'PHYSICAL_OPD',
      heightCm: 96.0,
      weightKg: 14.5,
      temperatureF: 100.4,
      pulseRate: 106,
      pediatricBmi: 15.7,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Right ear pain & pulling', 'High fever x 2 days', 'Snoring during sleep'],
      clinicalObservations: 'Right tympanic membrane congested, bulging, loss of light reflex. Nasal turbinates swollen.',
      diagnosis: 'Acute Otitis Media (Right Ear) & Adenoid Hypertrophy',
      doctorNotes: 'Prescribed pediatric Augmentin syrup and decongestant nasal drops. Avoid water entering right ear canal.',
      followUpDate: '2026-06-16',
      status: 'FINALIZED',
      createdAt: '2026-06-11 11:30:00',
      updatedAt: '2026-06-11 11:30:00',
      prescription: {
        id: 'rx-10',
        encounterId: 'enc-10',
        prescriptionNumber: 'RX-SDCH-2026-000061',
        childId: 'c8-1',
        childPermanentId: 'DM-SDCH-000112',
        childName: 'Sai',
        childAge: 3,
        childGender: 'Boy',
        weightKg: 14.5,
        heightCm: 96.0,
        temperatureF: 100.4,
        pulseRate: 106,
        pediatricBmi: 15.7,
        bloodGroup: 'AB+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-06-11',
        version: 1,
        diagnosis: 'Acute Otitis Media (Right Ear) & Adenoid Hypertrophy',
        allergyBannerSnapshot: ['House Dust & Pollen Grains (Perennial allergic rhinitis, mouth breathing & itchy eyes)'],
        items: [
          {
            id: 'rxi-19',
            medicineName: 'Amoxicillin + Potassium Clavulanate (Augmentin Duo)',
            genericName: 'Amoxicillin 200mg + Clavulanic Acid 28.5mg/5ml',
            form: 'SYRUP',
            strength: '228.5mg/5ml',
            dosage: '4 ml',
            frequency: 'TWICE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 5,
            timeSlots: ['Morning', 'Night'],
            instructionEn: 'Give 4 ml twice daily with food for 5 complete days.',
            instructionTe: 'ఆహారం తిన్న తర్వాత ఉదయం 4 ml, రాత్రి 4 ml చొప్పున 5 రోజుల పాటు క్రమం తప్పకుండా ఇవ్వండి.',
          },
          {
            id: 'rxi-20',
            medicineName: 'Saline Pediatric Nasal Spray (Nasoclear)',
            genericName: 'Sodium Chloride 0.65%',
            form: 'DROPS',
            strength: '0.65%',
            dosage: '2 sprays',
            frequency: 'THRICE_DAILY',
            timing: 'BEFORE_FOOD',
            durationDays: 7,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: '2 sprays in each nostril thrice daily to relieve Eustachian blockage.',
            instructionTe: 'ముక్కు దిబ్బడ మరియు చెవి నొప్పి తగ్గడానికి రెండు రంధ్రాలలో 2 స్ప్రేలు చొప్పున వేయండి.',
          },
        ],
        specialNotesEn: 'Keep ear completely dry during bath. Do not insert cotton buds or oil into ear canal.',
        specialNotesTe: 'చెవిలో నీరు లేదా నూనె పోయవద్దు. స్నానం చేసేటప్పుడు చెవిలోకి నీరు వెళ్లకుండా దూది పెట్టండి.',
        followUpDate: '2026-06-16',
        status: 'FINALIZED',
        createdAt: '2026-06-11 11:30:00',
        updatedAt: '2026-06-11 11:30:00',
      },
    },

    // Encounter 11: Tara (Acute Enteritis & Dehydration)
    {
      id: 'enc-11',
      appointmentId: 'apt-9',
      childId: 'c9-1',
      childPermanentId: 'DM-SDCH-000113',
      childName: 'Tara',
      parentId: 'p9',
      parentName: 'Deepika',
      parentMobile: '9000000009',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      date: '2026-07-29',
      visitType: 'PHYSICAL_OPD',
      heightCm: 93.0,
      weightKg: 13.0,
      temperatureF: 99.2,
      pulseRate: 104,
      pediatricBmi: 15.0,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Watery diarrhea x 5 episodes', 'Mild nausea', 'Lethargy'],
      clinicalObservations: 'Sunken eyes mild, skin turgor elastic, mucous membranes moist. Alert and oriented.',
      diagnosis: 'Acute Viral Gastroenteritis with Mild Dehydration',
      doctorNotes: 'Advised WHO-ORS rehydration protocol, zinc sachet for 14 days, and light khichdi with curd.',
      followUpDate: '2026-08-01',
      status: 'FINALIZED',
      createdAt: '2026-07-29 12:15:00',
      updatedAt: '2026-07-29 12:15:00',
      prescription: {
        id: 'rx-11',
        encounterId: 'enc-11',
        prescriptionNumber: 'RX-SDCH-2026-000105',
        childId: 'c9-1',
        childPermanentId: 'DM-SDCH-000113',
        childName: 'Tara',
        childAge: 3,
        childGender: 'Girl',
        weightKg: 13.0,
        heightCm: 93.0,
        temperatureF: 99.2,
        pulseRate: 104,
        pediatricBmi: 15.0,
        bloodGroup: 'O+',
        doctorId: 'dr-subba-rao',
        doctorName: 'Dr. Subba Rao Vadarevu',
        doctorRegNo: 'APMC-38492',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-07-29',
        version: 1,
        diagnosis: 'Acute Viral Gastroenteritis with Mild Dehydration',
        allergyBannerSnapshot: ['Lactose & Cow Milk Protein (Abdominal distension, cramps & acidic loose stools)'],
        items: [
          {
            id: 'rxi-21',
            medicineName: 'WHO Low Osmolarity ORS (Electral / Prolyte)',
            genericName: 'Oral Rehydration Salts IP',
            form: 'DROPS',
            strength: 'WHO Formula',
            dosage: '100 ml',
            frequency: 'SOS',
            timing: 'AFTER_FOOD',
            durationDays: 4,
            timeSlots: ['Morning', 'Afternoon', 'Night'],
            instructionEn: 'Give 100 ml slowly in sips after each loose stool.',
            instructionTe: 'ప్రతి విరేచనం తర్వాత 100 ml ఓఆర్ఎస్ నీరు కొద్దికొద్దిగా తాగించండి.',
          },
          {
            id: 'rxi-22',
            medicineName: 'Zinc Gluconate Syrup (Zinconia 20)',
            genericName: 'Zinc Gluconate 20mg/5ml',
            form: 'SYRUP',
            strength: '20mg/5ml',
            dosage: '5 ml',
            frequency: 'ONCE_DAILY',
            timing: 'AFTER_FOOD',
            durationDays: 14,
            timeSlots: ['Morning'],
            instructionEn: 'Give 5 ml once daily for 14 days to reduce stool frequency and restore gut health.',
            instructionTe: 'ఉదయం భోజనం తర్వాత 5 ml జింక్ సిరప్ రోజుకు ఒకసారి 14 రోజుల పాటు తప్పక ఇవ్వండి.',
          },
        ],
        specialNotesEn: 'Continue soft bland diet like curd rice, banana, and coconut water. Avoid oily food.',
        specialNotesTe: 'పెరుగన్నం, అరటిపండు, కొబ్బరినీళ్లు ఇవ్వండి. నూనె పదార్థాలు పూర్తిగా మానండి.',
        followUpDate: '2026-08-01',
        status: 'FINALIZED',
        createdAt: '2026-07-29 12:15:00',
        updatedAt: '2026-07-29 12:15:00',
      },
    },

    // Encounter 12: Anika (Recurrent Allergic Bronchitis - Dr. Prashant)
    {
      id: 'enc-12',
      appointmentId: 'apt-10',
      childId: 'c10-1',
      childPermanentId: 'DM-SDCH-000115',
      childName: 'Anika',
      parentId: 'p10',
      parentName: 'Praveen',
      parentMobile: '9000000010',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      date: '2026-08-10',
      visitType: 'PHYSICAL_OPD',
      heightCm: 93.0,
      weightKg: 13.0,
      temperatureF: 98.6,
      pulseRate: 98,
      pediatricBmi: 15.0,
      growthStatus: 'HEALTHY',
      chiefComplaints: ['Nocturnal coughing fits x 1 week', 'Wheeze on exertion'],
      clinicalObservations: 'Chest bilateral scattered end-expiratory polyphonic wheeze. Good air exchange.',
      diagnosis: 'Recurrent Allergic Bronchitis & Reactive Wheeze',
      doctorNotes: 'Prescribed Monticope syrup at bedtime and Levolin inhaler SOS with spacer. Reviewed inhaler technique with mother.',
      followUpDate: '2026-08-24',
      status: 'FINALIZED',
      createdAt: '2026-08-10 16:45:00',
      updatedAt: '2026-08-10 16:45:00',
      prescription: {
        id: 'rx-12',
        encounterId: 'enc-12',
        prescriptionNumber: 'RX-SDCH-2026-000118',
        childId: 'c10-1',
        childPermanentId: 'DM-SDCH-000115',
        childName: 'Anika',
        childAge: 3,
        childGender: 'Girl',
        weightKg: 13.0,
        heightCm: 93.0,
        temperatureF: 98.6,
        pulseRate: 98,
        pediatricBmi: 15.0,
        bloodGroup: 'B+',
        doctorId: 'dr-prashant',
        doctorName: 'Dr. Prashant',
        doctorRegNo: 'APMC-45120',
        hospitalName: 'Sri Devi Children Hospital',
        branchId: 'kakinada',
        date: '2026-08-10',
        version: 1,
        diagnosis: 'Recurrent Allergic Bronchitis & Reactive Wheeze',
        allergyBannerSnapshot: ['Mustard & Egg Yolk (Perioral urticarial erythema & sneezing)'],
        items: [
          {
            id: 'rxi-23',
            medicineName: 'Montelukast + Levocetirizine Syrup (Monticope)',
            genericName: 'Montelukast 4mg + Levocetirizine 2.5mg/5ml',
            form: 'SYRUP',
            strength: '5ml',
            dosage: '5 ml',
            frequency: 'ONCE_DAILY',
            timing: 'AT_BEDTIME',
            durationDays: 10,
            timeSlots: ['Night'],
            instructionEn: 'Give 5 ml at bedtime for 10 nights to suppress allergic bronchospasm.',
            instructionTe: 'రాత్రి పడుకునే ముందు 5 ml సిరప్ 10 రోజుల పాటు రోజుకు ఒకసారి ఇవ్వండి.',
          },
          {
            id: 'rxi-24',
            medicineName: 'Levosalbutamol Inhaler (Levolin 50mcg)',
            genericName: 'Levosalbutamol 50mcg/puff',
            form: 'INHALER',
            strength: '50mcg',
            dosage: '2 puffs',
            frequency: 'SOS',
            timing: 'BEFORE_FOOD',
            durationDays: 7,
            timeSlots: ['Morning', 'Night'],
            instructionEn: '2 puffs with mask spacer only if night cough or difficulty breathing occurs.',
            instructionTe: 'రాత్రి దగ్గు లేదా ఆయాసం వచ్చినప్పుడు మాత్రమే మాస్క్ స్పేసర్ ద్వారా 2 పఫ్స్ ఇవ్వండి.',
          },
        ],
        specialNotesEn: 'Keep child away from dust, incense smoke, and cold beverages. Warm water sips.',
        specialNotesTe: 'ధూపం, అగరుబత్తీ పొగ తగలకుండా చూడండి. చల్లటి నీరు, ఐస్ క్రీములు ఇవ్వవద్దు.',
        followUpDate: '2026-08-24',
        status: 'FINALIZED',
        createdAt: '2026-08-10 16:45:00',
        updatedAt: '2026-08-10 16:45:00',
      },
    },
  ];
}

export function getDemoAppointments(today: string): Appointment[] {
  const [yyyy, mm, dd] = today.split('-');
  const ddmmyy = `${dd}${mm}${yyyy.slice(-2)}`;

  return [
    // -------------------------------------------------------------
    // DR. SUBBA RAO VADAREVU - KAKINADA BRANCH (OPD 10:00 - 13:00)
    // ALL 10 PRIMARY TEST CHILDREN BOOKED AT VARIOUS TIMES
    // -------------------------------------------------------------

    // 10:00 AM - Child 1: Aarav Kumar (Completed consultation)
    {
      id: 'apt-1',
      appointmentNumber: `SD-K-${ddmmyy}-1000`,
      childId: 'c1-1',
      childName: 'Aarav Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '10:00',
      expectedConsultationTime: '10:00',
      recommendedArrivalTime: '09:45',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 104.0,
      weightKg: 16.2,
      temperatureF: 98.6,
      pulseRate: 98,
      pediatricBmi: 15.0,
      actualArrivalTime: '09:44',
      consultationStartTime: '10:02',
      consultationEndTime: '10:16',
      consultationDurationMinutes: 14,
      createdAt: `${today} 08:00:00`,
      updatedAt: `${today} 10:16:00`,
    },

    // 10:15 AM - Child 2: Vihaan Babu (Completed consultation)
    {
      id: 'apt-2',
      appointmentNumber: `SD-K-${ddmmyy}-1015`,
      childId: 'c2-1',
      childName: 'Vihaan Babu',
      parentId: 'p2',
      parentName: 'Suresh Babu',
      parentMobile: '9000000002',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '10:15',
      expectedConsultationTime: '10:16',
      recommendedArrivalTime: '10:00',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 87.0,
      weightKg: 12.0,
      temperatureF: 99.1,
      pulseRate: 106,
      pediatricBmi: 15.9,
      actualArrivalTime: '10:05',
      consultationStartTime: '10:16',
      consultationEndTime: '10:29',
      consultationDurationMinutes: 13,
      createdAt: `${today} 08:15:00`,
      updatedAt: `${today} 10:29:00`,
    },

    // 10:30 AM - Child 3: Ananya Devi (Completed consultation)
    {
      id: 'apt-3',
      appointmentNumber: `SD-K-${ddmmyy}-1030`,
      childId: 'c3-1',
      childName: 'Ananya Devi',
      parentId: 'p3',
      parentName: 'Lakshmi Devi',
      parentMobile: '9000000003',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '10:30',
      expectedConsultationTime: '10:30',
      recommendedArrivalTime: '10:15',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 108.0,
      weightKg: 18.0,
      temperatureF: 98.4,
      pulseRate: 94,
      pediatricBmi: 15.4,
      actualArrivalTime: '10:12',
      consultationStartTime: '10:30',
      consultationEndTime: '10:44',
      consultationDurationMinutes: 14,
      createdAt: `${today} 08:30:00`,
      updatedAt: `${today} 10:44:00`,
    },

    // 10:45 AM - Child 4: Ishaan Kumar (Currently WITH DOCTOR)
    {
      id: 'apt-4',
      appointmentNumber: `SD-K-${ddmmyy}-1045`,
      childId: 'c4-1',
      childName: 'Ishaan Kumar',
      parentId: 'p4',
      parentName: 'Rajesh Kumar',
      parentMobile: '9000000004',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '10:45',
      expectedConsultationTime: '10:45',
      recommendedArrivalTime: '10:30',
      status: 'WITH_DOCTOR',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 89.5,
      weightKg: 13.9,
      temperatureF: 99.0,
      pulseRate: 98,
      pediatricBmi: 17.3,
      actualArrivalTime: '10:28',
      consultationStartTime: '10:45',
      createdAt: `${today} 08:45:00`,
      updatedAt: `${today} 10:45:00`,
    },

    // 11:00 AM - Child 5: Myra Rao (Checked in & WAITING - Next in line)
    {
      id: 'apt-5',
      appointmentNumber: `SD-K-${ddmmyy}-1100`,
      childId: 'c5-1',
      childName: 'Myra Rao',
      parentId: 'p5',
      parentName: 'Priya Rao',
      parentMobile: '9000000005',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '11:00',
      expectedConsultationTime: '11:00',
      recommendedArrivalTime: '10:45',
      status: 'WAITING',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 95.0,
      weightKg: 14.2,
      temperatureF: 98.4,
      pulseRate: 98,
      pediatricBmi: 15.7,
      actualArrivalTime: '10:40',
      positionInQueue: 1,
      childrenAhead: 0,
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 10:40:00`,
    },

    // 11:15 AM - Child 6: Arjun (Checked in & WAITING - Second in line)
    {
      id: 'apt-6',
      appointmentNumber: `SD-K-${ddmmyy}-1115`,
      childId: 'c6-1',
      childName: 'Arjun',
      parentId: 'p6',
      parentName: 'Mahesh',
      parentMobile: '9000000006',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '11:15',
      expectedConsultationTime: '11:15',
      recommendedArrivalTime: '11:00',
      status: 'WAITING',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 96.5,
      weightKg: 15.0,
      temperatureF: 98.8,
      pulseRate: 100,
      pediatricBmi: 16.1,
      actualArrivalTime: '10:52',
      positionInQueue: 2,
      childrenAhead: 1,
      createdAt: `${today} 09:10:00`,
      updatedAt: `${today} 10:52:00`,
    },

    // 11:30 AM - Child 7: Kavya (ARRIVED at reception desk)
    {
      id: 'apt-7',
      appointmentNumber: `SD-K-${ddmmyy}-1130`,
      childId: 'c7-1',
      childName: 'Kavya',
      parentId: 'p7',
      parentName: 'Sravani',
      parentMobile: '9000000007',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '11:30',
      expectedConsultationTime: '11:30',
      recommendedArrivalTime: '11:15',
      status: 'ARRIVED',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 101.5,
      weightKg: 12.1,
      temperatureF: 98.6,
      pulseRate: 102,
      pediatricBmi: 11.7,
      actualArrivalTime: '11:05',
      positionInQueue: 3,
      childrenAhead: 2,
      createdAt: `${today} 09:15:00`,
      updatedAt: `${today} 11:05:00`,
    },

    // 11:45 AM - Child 8: Sai (APPROACHING hospital / near token alert)
    {
      id: 'apt-8',
      appointmentNumber: `SD-K-${ddmmyy}-1145`,
      childId: 'c8-1',
      childName: 'Sai',
      parentId: 'p8',
      parentName: 'Venkatesh',
      parentMobile: '9000000008',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '11:45',
      expectedConsultationTime: '11:45',
      recommendedArrivalTime: '11:30',
      status: 'APPROACHING',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 4,
      childrenAhead: 3,
      createdAt: `${today} 09:20:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // 12:00 PM - Child 9: Tara (BOOKED online)
    {
      id: 'apt-9',
      appointmentNumber: `SD-K-${ddmmyy}-1200`,
      childId: 'c9-1',
      childName: 'Tara',
      parentId: 'p9',
      parentName: 'Deepika',
      parentMobile: '9000000009',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '12:00',
      expectedConsultationTime: '12:00',
      recommendedArrivalTime: '11:45',
      status: 'BOOKED',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 5,
      childrenAhead: 4,
      createdAt: `${today} 09:25:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // 12:15 PM - Child 10: Anika (BOOKED online)
    {
      id: 'apt-10',
      appointmentNumber: `SD-K-${ddmmyy}-1215`,
      childId: 'c10-1',
      childName: 'Anika',
      parentId: 'p10',
      parentName: 'Praveen',
      parentMobile: '9000000010',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '12:15',
      expectedConsultationTime: '12:15',
      recommendedArrivalTime: '12:00',
      status: 'BOOKED',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 6,
      childrenAhead: 5,
      createdAt: `${today} 09:30:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // 12:30 PM - Diya Kumar (Infant Case booked)
    {
      id: 'apt-12',
      appointmentNumber: `SD-K-${ddmmyy}-1230`,
      childId: 'c1-2',
      childName: 'Diya Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '12:30',
      expectedConsultationTime: '12:30',
      recommendedArrivalTime: '12:15',
      status: 'BOOKED',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 7,
      childrenAhead: 6,
      createdAt: `${today} 09:35:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // -------------------------------------------------------------
    // DR. PRASHANT - SENIOR PEDIATRICIAN QUEUE (KAKINADA BRANCH)
    // -------------------------------------------------------------

    // 10:00 AM - Diya Kumar (Infant CMPA & Weaning - Completed)
    {
      id: 'apt-p1',
      appointmentNumber: `SD-K-${ddmmyy}-P1000`,
      childId: 'c1-2',
      childName: 'Diya Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '10:00',
      expectedConsultationTime: '10:00',
      recommendedArrivalTime: '09:45',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 75.0,
      weightKg: 9.6,
      actualArrivalTime: '09:45',
      consultationStartTime: '10:00',
      consultationEndTime: '10:15',
      consultationDurationMinutes: 15,
      createdAt: `${today} 08:00:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // 10:30 AM - Aditya Devi (1y Infant - Febrile Seizure Review - WITH DOCTOR)
    {
      id: 'apt-p2',
      appointmentNumber: `SD-K-${ddmmyy}-P1030`,
      childId: 'c3-2',
      childName: 'Aditya Devi',
      parentId: 'p3',
      parentName: 'Lakshmi Devi',
      parentMobile: '9000000003',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '10:30',
      expectedConsultationTime: '10:30',
      recommendedArrivalTime: '10:15',
      status: 'WITH_DOCTOR',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 76.0,
      weightKg: 10.2,
      temperatureF: 99.4,
      pulseRate: 114,
      actualArrivalTime: '10:20',
      consultationStartTime: '10:30',
      createdAt: `${today} 08:30:00`,
      updatedAt: `${today} 10:30:00`,
    },

    // 11:00 AM - Riya Rao (1y Infant - Eczema - WAITING)
    {
      id: 'apt-p3',
      appointmentNumber: `SD-K-${ddmmyy}-P1100`,
      childId: 'c5-2',
      childName: 'Riya Rao',
      parentId: 'p5',
      parentName: 'Priya Rao',
      parentMobile: '9000000005',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '11:00',
      expectedConsultationTime: '11:00',
      recommendedArrivalTime: '10:45',
      status: 'WAITING',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 74.0,
      weightKg: 9.1,
      actualArrivalTime: '10:48',
      positionInQueue: 1,
      childrenAhead: 0,
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 10:48:00`,
    },

    // 11:30 AM - Karthik (2y Toddler - Growth Faltering - ARRIVED)
    {
      id: 'apt-p4',
      appointmentNumber: `SD-K-${ddmmyy}-P1130`,
      childId: 'c7-2',
      childName: 'Karthik',
      parentId: 'p7',
      parentName: 'Sravani',
      parentMobile: '9000000007',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '11:30',
      expectedConsultationTime: '11:30',
      recommendedArrivalTime: '11:15',
      status: 'ARRIVED',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 84.0,
      weightKg: 10.8,
      actualArrivalTime: '11:10',
      positionInQueue: 2,
      childrenAhead: 1,
      createdAt: `${today} 09:15:00`,
      updatedAt: `${today} 11:10:00`,
    },

    // 12:00 PM - Nikhil (1y Infant - Toddler Bronchiolitis - BOOKED)
    {
      id: 'apt-p5',
      appointmentNumber: `SD-K-${ddmmyy}-P1200`,
      childId: 'c9-2',
      childName: 'Nikhil',
      parentId: 'p9',
      parentName: 'Deepika',
      parentMobile: '9000000009',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '12:00',
      expectedConsultationTime: '12:00',
      recommendedArrivalTime: '11:45',
      status: 'BOOKED',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 3,
      childrenAhead: 2,
      createdAt: `${today} 09:20:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // 16:30 PM - Anika (Senior Pediatric Evening Clinic - BOOKED)
    {
      id: 'apt-p6',
      appointmentNumber: `SD-K-${ddmmyy}-P1630`,
      childId: 'c10-1',
      childName: 'Anika',
      parentId: 'p10',
      parentName: 'Praveen',
      parentMobile: '9000000010',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'kakinada',
      branchName: 'Sri Devi Children Hospital - Kakinada',
      date: today,
      bookedTime: '16:30',
      expectedConsultationTime: '16:30',
      recommendedArrivalTime: '16:15',
      status: 'BOOKED',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 1,
      childrenAhead: 0,
      createdAt: `${today} 09:30:00`,
      updatedAt: `${today} 10:15:00`,
    },

    // -------------------------------------------------------------
    // PITHAPURAM BRANCH DEMO APPOINTMENTS
    // -------------------------------------------------------------
    {
      id: 'apt-pith-1',
      appointmentNumber: `SD-P-${ddmmyy}-1000`,
      childId: 'c1-1',
      childName: 'Aarav Kumar',
      parentId: 'p1',
      parentName: 'Ravi Kumar',
      parentMobile: '9000000001',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'pithapuram',
      branchName: 'Sri Devi Children Hospital - Pithapuram',
      date: today,
      bookedTime: '10:00',
      expectedConsultationTime: '10:00',
      recommendedArrivalTime: '09:45',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 104.0,
      weightKg: 16.2,
      actualArrivalTime: '09:45',
      consultationStartTime: '10:00',
      consultationEndTime: '10:15',
      consultationDurationMinutes: 15,
      createdAt: `${today} 08:00:00`,
      updatedAt: `${today} 10:15:00`,
    },
    {
      id: 'apt-pith-2',
      appointmentNumber: `SD-P-${ddmmyy}-1030`,
      childId: 'c3-1',
      childName: 'Ananya Devi',
      parentId: 'p3',
      parentName: 'Lakshmi Devi',
      parentMobile: '9000000003',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'pithapuram',
      branchName: 'Sri Devi Children Hospital - Pithapuram',
      date: today,
      bookedTime: '10:30',
      expectedConsultationTime: '10:30',
      recommendedArrivalTime: '10:15',
      status: 'WITH_DOCTOR',
      paymentStatus: 'PAID',
      paymentMethod: 'PHONEPE',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 108.0,
      weightKg: 18.0,
      actualArrivalTime: '10:15',
      consultationStartTime: '10:30',
      createdAt: `${today} 08:30:00`,
      updatedAt: `${today} 10:30:00`,
    },
    {
      id: 'apt-pith-3',
      appointmentNumber: `SD-P-${ddmmyy}-1115`,
      childId: 'c6-1',
      childName: 'Arjun',
      parentId: 'p6',
      parentName: 'Mahesh',
      parentMobile: '9000000006',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      branchId: 'pithapuram',
      branchName: 'Sri Devi Children Hospital - Pithapuram',
      date: today,
      bookedTime: '11:15',
      expectedConsultationTime: '11:15',
      recommendedArrivalTime: '11:00',
      status: 'WAITING',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      heightCm: 96.5,
      weightKg: 15.0,
      actualArrivalTime: '10:55',
      positionInQueue: 1,
      childrenAhead: 0,
      createdAt: `${today} 09:00:00`,
      updatedAt: `${today} 10:55:00`,
    },
    {
      id: 'apt-pith-4',
      appointmentNumber: `SD-P-${ddmmyy}-P1200`,
      childId: 'c10-1',
      childName: 'Anika',
      parentId: 'p10',
      parentName: 'Praveen',
      parentMobile: '9000000010',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      branchId: 'pithapuram',
      branchName: 'Sri Devi Children Hospital - Pithapuram',
      date: today,
      bookedTime: '12:00',
      expectedConsultationTime: '12:00',
      recommendedArrivalTime: '11:45',
      status: 'BOOKED',
      paymentStatus: 'PENDING',
      bookingSource: 'ONLINE',
      
      advanceNoticePreferenceMinutes: 30,
      history: [],
      positionInQueue: 1,
      childrenAhead: 0,
      createdAt: `${today} 09:20:00`,
      updatedAt: `${today} 10:15:00`,
    },
  ];
}

/**
 * Ensures that the in-memory DatabaseState has all comprehensive demo data:
 * - Dr. Prashant upgraded to senior pediatrician credentials
 * - All 10 test kids have full allergies, chronic conditions, growth records & past prescriptions
 * - Today's appointments cover all 10 kids at various times across morning and afternoon OPD
 */
export function ensureComprehensiveDemoData(state: DatabaseState): void {
  const targetDate = state.config?.simulatedDate || new Date().toISOString().split('T')[0];

  // 1. Upgrade Dr. Prashant's credentials to match Dr. Subba Rao
  const prashantDoc = state.doctors.find((d) => d.id === 'dr-prashant');
  if (prashantDoc) {
    prashantDoc.qualifications = 'MBBS, MD (Pediatrics), DCH, FIAP';
    prashantDoc.specialty = 'Senior Consultant Pediatrician & Neonatologist';
    prashantDoc.experienceYears = 24;
    prashantDoc.summary =
      'Senior experienced pediatrician with 24+ years of clinical excellence in neonatal intensive care, pediatric infectious diseases, pediatric asthma, and growth development.';
    prashantDoc.medicalRegistrationNo = 'APMC-45120';
  }

  const prashantAccount = state.doctorAccounts.find((a) => a.doctorId === 'dr-prashant');
  if (prashantAccount) {
    prashantAccount.medicalRegistrationNo = 'APMC-45120';
  }

  // 2. Merge Allergies
  const demoAllergies = getDemoAllergies(targetDate);
  const existingAlgMap = new Map(state.allergies.map((a) => [a.id, a]));
  for (const alg of demoAllergies) {
    existingAlgMap.set(alg.id, alg);
  }
  state.allergies = Array.from(existingAlgMap.values());

  // 3. Merge Conditions
  const demoConditions = getDemoConditions(targetDate);
  const existingCndMap = new Map(state.conditions.map((c) => [c.id, c]));
  for (const cnd of demoConditions) {
    existingCndMap.set(cnd.id, cnd);
  }
  state.conditions = Array.from(existingCndMap.values());

  // 4. Merge Growth Records
  const demoGrowth = getDemoGrowthRecords(targetDate);
  const existingGrMap = new Map(state.growthRecords.map((g) => [g.id, g]));
  for (const gr of demoGrowth) {
    existingGrMap.set(gr.id, gr);
  }
  state.growthRecords = Array.from(existingGrMap.values());

  // 5. Merge Past Encounters & Prescriptions
  const demoEncounters = getDemoEncounters(targetDate);
  const existingEncMap = new Map(state.encounters.map((e) => [e.id, e]));
  for (const enc of demoEncounters) {
    existingEncMap.set(enc.id, enc);
  }
  state.encounters = Array.from(existingEncMap.values());

  // 6. Ensure Active Doctor Sessions exist for both doctors
  const doctors = ['dr-subba-rao', 'dr-prashant'];
  const branches = ['kakinada', 'pithapuram'];
  for (const docId of doctors) {
    for (const bId of branches) {
      const hasSession = state.sessions.some(
        (s) => s.doctorId === docId && s.branchId === bId && s.date === targetDate
      );
      if (!hasSession) {
        state.sessions.push({
          doctorId: docId,
          branchId: bId as any,
          date: targetDate,
          scheduledStart: '10:00',
          actualStart: docId === 'dr-subba-rao' ? '10:00' : '10:00',
          status: 'IN_SESSION',
          currentAppointmentId: docId === 'dr-subba-rao' ? 'apt-4' : 'apt-p2',
          currentDelayMinutes: 0,
          avgConsultationDurationMinutes: 14,
          bufferAvailableMinutes: 20,
          emergencyAdjustmentCount: 0,
        });
      }
    }
  }

  // 7. Ensure Appointments for all 10 kids on targetDate
  const demoAppointments = getDemoAppointments(targetDate);
  const existingApptMap = new Map(state.appointments.map((a) => [a.id, a]));

  for (const appt of demoAppointments) {
    const existing = existingApptMap.get(appt.id);
    if (!existing || existing.date !== targetDate) {
      existingApptMap.set(appt.id, appt);
    }
  }

  // Also check if any appointment with targetDate has old dates and update
  state.appointments = Array.from(existingApptMap.values());
}
