import Database from 'better-sqlite3';
import path from 'path';
function getLocalDateString(d = new Date()) {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

const dbPath = path.join(process.cwd(), 'hospital.db');
console.log('Seeding demo data into SQLite database at:', dbPath);

const db = new Database(dbPath);
db.pragma('journal_mode = WAL');

const today = getLocalDateString();
const [yyyy, mm, dd] = today.split('-');
const ddmmyy = `${dd}${mm}${yyyy.slice(-2)}`;

// 1. Update Dr. Prashant's profile to Senior Pediatrician
console.log("1. Updating Dr. Prashant's profile to Senior Pediatrician...");
db.prepare(`
  UPDATE doctors
  SET qualifications = 'MBBS, MD (Pediatrics), DCH, FIAP',
      specialty = 'Senior Consultant Pediatrician & Neonatologist',
      experience_years = 24,
      summary = 'Senior experienced pediatrician with 24+ years of clinical excellence in neonatal intensive care, pediatric infectious diseases, pediatric asthma, and growth development.',
      medical_registration_no = 'APMC-45120'
  WHERE id = 'dr-prashant'
`).run();

db.prepare(`
  UPDATE doctor_accounts
  SET medical_registration_no = 'APMC-45120'
  WHERE id = 'dr-prashant' OR doctor_id = 'dr-prashant'
`).run();

// 2. Insert comprehensive allergies across kids
console.log('2. Inserting comprehensive pediatric allergies for demo...');
const allergies = [
  {
    id: 'alg-1',
    childId: 'c1-1', // Aarav Kumar
    allergyType: 'MEDICINE',
    substance: 'Amoxicillin & Penicillin Group',
    reaction: 'Severe urticaria, lip swelling & facial hives',
    severity: 'SEVERE',
    status: 'ACTIVE',
    identifiedDate: '2026-05-10',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Severe allergic reaction to Augmentin oral syrup. Strict contraindication for penicillin class.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'alg-2',
    childId: 'c2-1', // Vihaan Babu
    allergyType: 'FOOD',
    substance: 'Peanuts & Tree Nuts',
    reaction: 'Perioral redness, itchy hives and swelling',
    severity: 'MODERATE',
    status: 'ACTIVE',
    identifiedDate: '2026-02-14',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Parent carries Cetirizine syrup as precaution. Avoid peanut butter and nut confectionaries.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'alg-3',
    childId: 'c2-1', // Vihaan Babu
    allergyType: 'MEDICINE',
    substance: 'Cotrimoxazole (Septran / Sulfa)',
    reaction: 'Maculopapular drug eruption on trunk',
    severity: 'MODERATE',
    status: 'ACTIVE',
    identifiedDate: '2026-04-18',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    notes: 'Rash noted after 3 days of Septran for UTI. Avoid sulfonamides.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'alg-4',
    childId: 'c3-1', // Ananya Devi
    allergyType: 'FOOD',
    substance: 'Egg Albumin (Eggs)',
    reaction: 'Cheek erythema & abdominal cramping',
    severity: 'MILD',
    status: 'ACTIVE',
    identifiedDate: '2025-10-05',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    notes: 'Tolerates baked goods in small amounts; avoid raw or boiled whole eggs.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'alg-5',
    childId: 'c1-2', // Diya Kumar (Infant)
    allergyType: 'FOOD',
    substance: "Cow's Milk Protein (CMPA)",
    reaction: 'Infantile eczema flare & curdy loose stools',
    severity: 'MODERATE',
    status: 'ACTIVE',
    identifiedDate: '2025-12-12',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Advised exclusive breastfeeding or extensively hydrolyzed infant formula.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'alg-6',
    childId: 'c4-1', // Ishaan Kumar
    allergyType: 'MEDICINE',
    substance: 'Cefixime (Cephalosporin)',
    reaction: 'Itchy papular rash over chest',
    severity: 'MODERATE',
    status: 'ACTIVE',
    identifiedDate: '2026-03-22',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Use macrolides (Azithromycin) or aminoglycosides when antibiotic indicated.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'alg-7',
    childId: 'c7-1', // Kavya
    allergyType: 'MEDICINE',
    substance: 'Ibuprofen & NSAIDs',
    reaction: 'Periorbital swelling and wheezing trigger',
    severity: 'SEVERE',
    status: 'ACTIVE',
    identifiedDate: '2026-01-30',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    notes: 'Strictly avoid Brufen/Ibugesic. Use Paracetamol for antipyresis.',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
];

const insertAlg = db.prepare(`
  INSERT OR REPLACE INTO child_allergies (id, child_id, data_json)
  VALUES (@id, @childId, @dataJson)
`);
for (const a of allergies) {
  insertAlg.run({ id: a.id, childId: a.childId, dataJson: JSON.stringify(a) });
}

// 3. Insert chronic conditions
console.log('3. Inserting chronic conditions...');
const conditions = [
  {
    id: 'cnd-1',
    childId: 'c1-1', // Aarav Kumar
    conditionName: 'Reactive Airway Disease & Recurrent Wheeze',
    category: 'RESPIRATORY',
    status: 'RECURRING',
    firstIdentifiedDate: '2026-04-12',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Triggered by seasonal cold and viral URIs. Advised warm water sips, steam inhalation, and Levolin inhaler SOS.',
    lastReviewedDate: '2026-07-22',
    followUpRecommendation: 'Review in 3 months or upon difficulty breathing',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'cnd-2',
    childId: 'c3-1', // Ananya Devi
    conditionName: 'Mild Childhood Bronchial Asthma',
    category: 'RESPIRATORY',
    status: 'ACTIVE',
    firstIdentifiedDate: '2025-11-20',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    notes: 'Controlled on Salbutamol + Budesonide inhaler with pediatric spacer. Avoid exposure to mosquito coils and agarbatti smoke.',
    lastReviewedDate: '2026-06-15',
    followUpRecommendation: '6-monthly pediatric pulmonology review',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'cnd-3',
    childId: 'c2-1', // Vihaan Babu
    conditionName: 'Febrile Seizure History (Single Episode)',
    category: 'NEUROLOGICAL',
    status: 'ACTIVE',
    firstIdentifiedDate: '2025-08-14',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Single generalized tonic-clonic seizure during 103°F viral fever. Prompt antipyresis advised whenever temp > 99.5°F.',
    lastReviewedDate: '2026-05-10',
    followUpRecommendation: 'Counsel parents on fever control and emergency SOS midazolam nasal spray',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'cnd-4',
    childId: 'c4-1', // Ishaan Kumar
    conditionName: 'Allergic Rhinitis with Adenoid Hypertrophy',
    category: 'ENT',
    status: 'ACTIVE',
    firstIdentifiedDate: '2026-01-10',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    notes: 'Mouth breathing during sleep, snoring. Salt water nasal rinse and nasal fluticasone spray.',
    lastReviewedDate: '2026-06-20',
    followUpRecommendation: 'ENT evaluation if snoring worsens',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
  {
    id: 'cnd-5',
    childId: 'c6-1', // Arjun
    conditionName: 'G6PD Deficiency (Hemolytic Risk)',
    category: 'HEMATOLOGY',
    status: 'ACTIVE',
    firstIdentifiedDate: '2024-04-05',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    notes: 'Enzyme deficiency confirmed on neonatal screening. Strict avoidance list provided to parents: no fava beans, primaquine, or high-dose aspirin.',
    lastReviewedDate: '2026-03-10',
    followUpRecommendation: 'Annual complete blood count and pediatric check',
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 09:00:00`,
  },
];

const insertCnd = db.prepare(`
  INSERT OR REPLACE INTO child_conditions (id, child_id, data_json)
  VALUES (@id, @childId, @dataJson)
`);
for (const c of conditions) {
  insertCnd.run({ id: c.id, childId: c.childId, dataJson: JSON.stringify(c) });
}

// 4. Insert growth records
console.log('4. Inserting multi-visit growth records for all kids...');
const growthRecords = [
  {
    id: 'gr-1',
    childId: 'c1-1',
    recordedDate: '2026-03-15',
    ageYears: 3,
    ageMonths: 8,
    heightCm: 99.0,
    weightKg: 14.8,
    pediatricBmi: 15.1,
    growthStatus: 'HEALTHY',
    interpretationText: 'Healthy pediatric growth range (50th percentile on IAP chart)',
    doctorConfirmed: true,
    recordedByRole: 'RECEPTIONIST',
    recordedByName: 'Kakinada Frontdesk',
  },
  {
    id: 'gr-2',
    childId: 'c1-1',
    recordedDate: '2026-07-22',
    ageYears: 4,
    ageMonths: 0,
    heightCm: 102.5,
    weightKg: 15.6,
    pediatricBmi: 14.9,
    heightDeltaCm: 3.5,
    weightDeltaKg: 0.8,
    growthStatus: 'HEALTHY',
    interpretationText: 'Consistent healthy growth trajectory.',
    doctorConfirmed: true,
    recordedByRole: 'DOCTOR',
    recordedByName: 'Dr. Subba Rao Vadarevu',
  },
  {
    id: 'gr-3',
    childId: 'c2-1',
    recordedDate: '2026-04-18',
    ageYears: 2,
    ageMonths: 3,
    heightCm: 86.5,
    weightKg: 11.8,
    pediatricBmi: 15.8,
    growthStatus: 'HEALTHY',
    interpretationText: 'Healthy height and weight milestones maintained.',
    doctorConfirmed: true,
    recordedByRole: 'DOCTOR',
    recordedByName: 'Dr. Prashant',
  },
  {
    id: 'gr-4',
    childId: 'c3-1',
    recordedDate: '2026-05-12',
    ageYears: 4,
    ageMonths: 6,
    heightCm: 106.0,
    weightKg: 17.5,
    pediatricBmi: 15.6,
    growthStatus: 'HEALTHY',
    interpretationText: 'Normal growth curve on WHO reference chart.',
    doctorConfirmed: true,
    recordedByRole: 'DOCTOR',
    recordedByName: 'Dr. Subba Rao Vadarevu',
  },
  {
    id: 'gr-5',
    childId: 'c1-2', // Diya infant
    recordedDate: '2026-02-10',
    ageYears: 1,
    ageMonths: 11,
    heightCm: 74.0,
    weightKg: 9.3,
    pediatricBmi: 17.0,
    growthStatus: 'HEALTHY',
    interpretationText: 'Infant growth milestones healthy. Head circumference normal.',
    doctorConfirmed: true,
    recordedByRole: 'DOCTOR',
    recordedByName: 'Dr. Subba Rao Vadarevu',
  },
  {
    id: 'gr-6',
    childId: 'c4-1', // Ishaan (Height is less demo)
    recordedDate: '2026-06-20',
    ageYears: 3,
    ageMonths: 9,
    heightCm: 89.0, // Expected ~95cm
    weightKg: 13.8,
    pediatricBmi: 17.4,
    growthStatus: 'REVIEW_ADVISED',
    interpretationText: 'Height is below 15th percentile for age. Advised morning sunlight, Vitamin D, and calcium.',
    doctorConfirmed: true,
    recordedByRole: 'DOCTOR',
    recordedByName: 'Dr. Subba Rao Vadarevu',
  },
  {
    id: 'gr-7',
    childId: 'c7-1', // Kavya (Weight is less demo)
    recordedDate: '2026-04-10',
    ageYears: 4,
    ageMonths: 3,
    heightCm: 101.0,
    weightKg: 12.2, // Expected 14-20kg
    pediatricBmi: 12.0,
    growthStatus: 'REVIEW_ADVISED',
    interpretationText: 'Weight below 5th percentile. Advised high-calorie nutritious diet: ragi malt, ghee, boiled eggs.',
    doctorConfirmed: true,
    recordedByRole: 'DOCTOR',
    recordedByName: 'Dr. Prashant',
  },
];

const insertGr = db.prepare(`
  INSERT OR REPLACE INTO pediatric_growth_records (id, child_id, data_json)
  VALUES (@id, @childId, @dataJson)
`);
for (const g of growthRecords) {
  insertGr.run({ id: g.id, childId: g.childId, dataJson: JSON.stringify(g) });
}

// 5. Insert rich past encounters and prescriptions across all kids
console.log('5. Inserting detailed past encounters & bilingual prescriptions...');
const encounters = [
  // Encounter 1: Aarav Kumar (Gastritis)
  {
    id: 'enc-1',
    appointmentId: 'apt-1',
    childId: 'c1-1',
    childPermanentId: 'DM-SDCH-000101',
    childName: 'Aarav Kumar',
    parentId: 'p1',
    parentName: 'Ravi Kumar',
    parentMobile: '9000000001',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    date: '2026-07-22',
    visitType: 'PHYSICAL_OPD',
    heightCm: 102.5,
    weightKg: 15.6,
    temperatureF: 98.6,
    pulseRate: 98,
    pediatricBmi: 14.9,
    growthStatus: 'HEALTHY',
    chiefComplaints: ['Vomiting x 3 episodes', 'Mild abdominal colic'],
    clinicalObservations: 'Abdomen soft, non-tender. Mild dehydration, alert and responsive.',
    diagnosis: 'Acute Gastritis with mild dehydration',
    doctorNotes: 'Advised oral rehydration solution (ORS), light bland diet, avoid milk products for 24h.',
    followUpDate: '2026-07-25',
    status: 'FINALIZED',
    createdAt: '2026-07-22 10:20:00',
    updatedAt: '2026-07-22 10:20:00',
    prescription: {
      id: 'rx-1',
      encounterId: 'enc-1',
      prescriptionNumber: 'RX-SDCH-2026-000084',
      childId: 'c1-1',
      childPermanentId: 'DM-SDCH-000101',
      childName: 'Aarav Kumar',
      childAge: 4,
      childGender: 'Boy',
      weightKg: 15.6,
      heightCm: 102.5,
      temperatureF: 98.6,
      pulseRate: 98,
      pediatricBmi: 14.9,
      bloodGroup: 'O+',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      doctorRegNo: 'APMC-38492',
      hospitalName: 'Sri Devi Children Hospital',
      branchId: 'kakinada',
      date: '2026-07-22',
      version: 1,
      diagnosis: 'Acute Gastritis with mild dehydration',
      allergyBannerSnapshot: ['Amoxicillin & Penicillin Group (Severe urticaria, lip swelling & facial hives)'],
      items: [
        {
          id: 'rxi-1',
          medicineName: 'Ondansetron Oral Solution (Emset)',
          genericName: 'Ondansetron 2mg/5ml',
          form: 'SYRUP',
          strength: '2mg/5ml',
          dosage: '3 ml',
          frequency: 'SOS',
          timing: 'BEFORE_FOOD',
          durationDays: 2,
          timeSlots: ['Morning', 'Afternoon', 'Night'],
          instructionEn: 'Give 3 ml 15 minutes before food only if child vomits.',
          instructionTe: 'వాంతులు అయినప్పుడు మాత్రమే భోజనానికి 15 నిమిషాల ముందు 3 ml ఇవ్వండి.',
        },
        {
          id: 'rxi-2',
          medicineName: 'Probiotic Zinc Sachet (Darolac / Econorm)',
          genericName: 'Saccharomyces boulardii + Zinc',
          form: 'DROPS',
          strength: '250mg',
          dosage: '1 sachet',
          frequency: 'TWICE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 5,
          timeSlots: ['Morning', 'Night'],
          instructionEn: 'Mix 1 sachet in lukewarm water or breastmilk twice daily for 5 days.',
          instructionTe: 'గోరువెచ్చని నీటిలో ఒక ప్యాకెట్ కలిపి రోజుకు రెండుసార్లు 5 రోజుల పాటు ఇవ్వండి.',
        },
      ],
      specialNotesEn: 'Plentiful sips of ORS after every vomiting episode. Avoid fruit juices for 24h.',
      specialNotesTe: 'ప్రతి వాంతి తర్వాత తరచుగా ఓఆర్ఎస్ (ORS) నీరు కొద్దికొద్దిగా తాగించండి.',
      followUpDate: '2026-07-25',
      status: 'FINALIZED',
      createdAt: '2026-07-22 10:20:00',
      updatedAt: '2026-07-22 10:20:00',
    },
  },

  // Encounter 2: Aarav Kumar (Wheezing Episode - Dr. Prashant)
  {
    id: 'enc-2',
    childId: 'c1-1',
    childPermanentId: 'DM-SDCH-000101',
    childName: 'Aarav Kumar',
    parentId: 'p1',
    parentName: 'Ravi Kumar',
    parentMobile: '9000000001',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    branchId: 'kakinada',
    date: '2026-05-10',
    visitType: 'PHYSICAL_OPD',
    heightCm: 101.0,
    weightKg: 15.2,
    temperatureF: 99.2,
    pulseRate: 104,
    pediatricBmi: 14.9,
    growthStatus: 'HEALTHY',
    chiefComplaints: ['Nocturnal dry cough', 'Mild expiratory wheeze'],
    clinicalObservations: 'Bilateral scattered rhonchi, air entry good. No subcostal retractions.',
    diagnosis: 'Reactive Bronchospasm & Viral URI',
    doctorNotes: 'Prescribed pediatric inhaler with spacer. Penicillin allergy confirmed and avoided.',
    followUpDate: '2026-05-17',
    status: 'FINALIZED',
    createdAt: '2026-05-10 11:30:00',
    updatedAt: '2026-05-10 11:30:00',
    prescription: {
      id: 'rx-2',
      encounterId: 'enc-2',
      prescriptionNumber: 'RX-SDCH-2026-000042',
      childId: 'c1-1',
      childPermanentId: 'DM-SDCH-000101',
      childName: 'Aarav Kumar',
      childAge: 4,
      childGender: 'Boy',
      weightKg: 15.2,
      heightCm: 101.0,
      temperatureF: 99.2,
      pulseRate: 104,
      pediatricBmi: 14.9,
      bloodGroup: 'O+',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      doctorRegNo: 'APMC-45120',
      hospitalName: 'Sri Devi Children Hospital',
      branchId: 'kakinada',
      date: '2026-05-10',
      version: 1,
      diagnosis: 'Reactive Bronchospasm & Viral URI',
      allergyBannerSnapshot: ['Amoxicillin & Penicillin Group (Severe)'],
      items: [
        {
          id: 'rxi-3',
          medicineName: 'Salbutamol Inhaler (Asthalin 100mcg)',
          genericName: 'Salbutamol 100mcg/puff',
          form: 'INHALER',
          strength: '100mcg',
          dosage: '2 puffs',
          frequency: 'THRICE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 5,
          timeSlots: ['Morning', 'Afternoon', 'Night'],
          instructionEn: 'Take 2 puffs via pediatric spacer with mask thrice daily for 5 days.',
          instructionTe: 'పీడియాట్రిక్ స్పేసర్ మాస్క్ ద్వారా రోజుకు 3 సార్లు 2 పఫ్స్ పీల్చండి.',
        },
        {
          id: 'rxi-4',
          medicineName: 'Montelukast Sodium Chewable (Montair 4mg)',
          genericName: 'Montelukast 4mg',
          form: 'TABLET',
          strength: '4mg',
          dosage: '1 tablet',
          frequency: 'ONCE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 14,
          timeSlots: ['Night'],
          instructionEn: 'Give 1 chewable tablet at bedtime for 14 days.',
          instructionTe: 'రాత్రి పడుకునే ముందు 1 మాత్ర నమలడానికి ఇవ్వండి (14 రోజులు).',
        },
      ],
      specialNotesEn: 'Avoid exposure to dust, smoke, incense, and cold foods.',
      specialNotesTe: 'చల్లని పదార్థాలు, దుమ్ము, పొగలకు దూరంగా ఉంచండి.',
      followUpDate: '2026-05-17',
      status: 'FINALIZED',
      createdAt: '2026-05-10 11:30:00',
      updatedAt: '2026-05-10 11:30:00',
    },
  },

  // Encounter 3: Vihaan Babu (Fever & URI - Dr. Subba Rao)
  {
    id: 'enc-3',
    childId: 'c2-1',
    childPermanentId: 'DM-SDCH-000103',
    childName: 'Vihaan Babu',
    parentId: 'p2',
    parentName: 'Suresh Babu',
    parentMobile: '9000000002',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    date: '2026-04-18',
    visitType: 'PHYSICAL_OPD',
    heightCm: 86.5,
    weightKg: 11.8,
    temperatureF: 101.4,
    pulseRate: 112,
    pediatricBmi: 15.8,
    growthStatus: 'HEALTHY',
    chiefComplaints: ['High fever 101.4°F x 2 days', 'Clear nasal discharge', 'Irritable'],
    clinicalObservations: 'Pharynx congested, tympanic membranes normal. Chest clear. No neck stiffness.',
    diagnosis: 'Acute Viral Pharyngitis & Rhinorrhea',
    doctorNotes: 'Parent cautioned on febrile seizure protocol. Tepid sponging advised if temp exceeds 101°F.',
    followUpDate: '2026-04-21',
    status: 'FINALIZED',
    createdAt: '2026-04-18 10:40:00',
    updatedAt: '2026-04-18 10:40:00',
    prescription: {
      id: 'rx-3',
      encounterId: 'enc-3',
      prescriptionNumber: 'RX-SDCH-2026-000031',
      childId: 'c2-1',
      childPermanentId: 'DM-SDCH-000103',
      childName: 'Vihaan Babu',
      childAge: 3,
      childGender: 'Boy',
      weightKg: 11.8,
      heightCm: 86.5,
      temperatureF: 101.4,
      pulseRate: 112,
      pediatricBmi: 15.8,
      bloodGroup: 'A+',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      doctorRegNo: 'APMC-38492',
      hospitalName: 'Sri Devi Children Hospital',
      branchId: 'kakinada',
      date: '2026-04-18',
      version: 1,
      diagnosis: 'Acute Viral Pharyngitis & Rhinorrhea',
      allergyBannerSnapshot: [
        'Peanuts & Tree Nuts (Moderate - perioral redness)',
        'Cotrimoxazole / Sulfa (Moderate - maculopapular rash)',
      ],
      items: [
        {
          id: 'rxi-5',
          medicineName: 'Paracetamol Suspension (Calpol 250mg)',
          genericName: 'Paracetamol 250mg/5ml',
          form: 'SYRUP',
          strength: '250mg/5ml',
          dosage: '3.5 ml',
          frequency: 'THRICE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 3,
          timeSlots: ['Morning', 'Afternoon', 'Night'],
          instructionEn: 'Give 3.5 ml every 6 to 8 hours when fever is above 99.5°F.',
          instructionTe: 'జ్వరం 99.5°F దాటినప్పుడు ప్రతి 6 నుండి 8 గంటలకు 3.5 ml ఇవ్వండి.',
        },
        {
          id: 'rxi-6',
          medicineName: 'Normal Saline Nasal Drops (Nasoclear)',
          genericName: 'Sodium Chloride 0.65%',
          form: 'DROPS',
          strength: '0.65%',
          dosage: '2 drops',
          frequency: 'THRICE_DAILY',
          timing: 'BEFORE_FOOD',
          durationDays: 5,
          timeSlots: ['Morning', 'Afternoon', 'Night'],
          instructionEn: 'Instill 2 drops in each nostril before feeding and at bedtime.',
          instructionTe: 'రెండు ముక్కు రంధ్రాలలో 2 చుక్కల చొప్పున పాలు తాగే ముందు వేయండి.',
        },
      ],
      specialNotesEn: 'Monitor temperature closely. Keep child in light cotton clothing.',
      specialNotesTe: 'జ్వరాన్ని క్రమం తప్పకుండా కొలవండి. మందపాటి దుస్తులు వేయవద్దు.',
      followUpDate: '2026-04-21',
      status: 'FINALIZED',
      createdAt: '2026-04-18 10:40:00',
      updatedAt: '2026-04-18 10:40:00',
    },
  },

  // Encounter 4: Ananya Devi (Asthma follow-up - Dr. Prashant)
  {
    id: 'enc-4',
    childId: 'c3-1',
    childPermanentId: 'DM-SDCH-000104',
    childName: 'Ananya Devi',
    parentId: 'p3',
    parentName: 'Lakshmi Devi',
    parentMobile: '9000000003',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    branchId: 'kakinada',
    date: '2026-06-15',
    visitType: 'PHYSICAL_OPD',
    heightCm: 106.0,
    weightKg: 17.5,
    temperatureF: 98.4,
    pulseRate: 92,
    pediatricBmi: 15.6,
    growthStatus: 'HEALTHY',
    chiefComplaints: ['Routine asthma control review', 'Occasional morning sneezing'],
    clinicalObservations: 'Chest clear, normal vesicular breath sounds. Good PEFR response. Active and cheerful.',
    diagnosis: 'Childhood Bronchial Asthma (Well Controlled)',
    doctorNotes: 'Continue maintenance inhaler. Egg allergy reviewed, parent adhering strictly.',
    followUpDate: '2026-09-15',
    status: 'FINALIZED',
    createdAt: '2026-06-15 11:00:00',
    updatedAt: '2026-06-15 11:00:00',
    prescription: {
      id: 'rx-4',
      encounterId: 'enc-4',
      prescriptionNumber: 'RX-SDCH-2026-000058',
      childId: 'c3-1',
      childPermanentId: 'DM-SDCH-000104',
      childName: 'Ananya Devi',
      childAge: 4,
      childGender: 'Girl',
      weightKg: 17.5,
      heightCm: 106.0,
      temperatureF: 98.4,
      pulseRate: 92,
      pediatricBmi: 15.6,
      bloodGroup: 'AB+',
      doctorId: 'dr-prashant',
      doctorName: 'Dr. Prashant',
      doctorRegNo: 'APMC-45120',
      hospitalName: 'Sri Devi Children Hospital',
      branchId: 'kakinada',
      date: '2026-06-15',
      version: 1,
      diagnosis: 'Childhood Bronchial Asthma (Well Controlled)',
      allergyBannerSnapshot: ['Egg Albumin (Mild erythema)'],
      items: [
        {
          id: 'rxi-7',
          medicineName: 'Budesonide Inhaler (Budecort 100mcg)',
          genericName: 'Budesonide 100mcg',
          form: 'INHALER',
          strength: '100mcg',
          dosage: '1 puff',
          frequency: 'TWICE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 30,
          timeSlots: ['Morning', 'Night'],
          instructionEn: '1 puff via spacer twice daily. Rinse mouth with water after inhalation.',
          instructionTe: 'స్పేసర్ ద్వారా రోజుకు 2 సార్లు 1 పఫ్ పీల్చండి. పీల్చిన తర్వాత నోరు పుక్కిలించండి.',
        },
        {
          id: 'rxi-8',
          medicineName: 'Multivitamin & Zinc Syrup (Zincovit)',
          genericName: 'Multivitamins with Zinc',
          form: 'SYRUP',
          strength: '5ml',
          dosage: '5 ml',
          frequency: 'ONCE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 30,
          timeSlots: ['Morning'],
          instructionEn: 'Give 5 ml once daily in morning for appetite and general immunity.',
          instructionTe: 'ఆకలి మరియు రోగనిరోధక శక్తి కోసం ఉదయం పూట 5 ml ఇవ్వండి.',
        },
      ],
      specialNotesEn: 'Ensure spacer is washed weekly with mild soap water. Do not scrub inside.',
      specialNotesTe: 'స్పేసర్‌ను వారానికి ఒకసారి గోరువెచ్చని నీటితో కడగండి.',
      followUpDate: '2026-09-15',
      status: 'FINALIZED',
      createdAt: '2026-06-15 11:00:00',
      updatedAt: '2026-06-15 11:00:00',
    },
  },

  // Encounter 5: Diya Kumar (Infant Colic & Growth Check - 10 Months)
  {
    id: 'enc-5',
    childId: 'c1-2',
    childPermanentId: 'DM-SDCH-000102',
    childName: 'Diya Kumar',
    parentId: 'p1',
    parentName: 'Ravi Kumar',
    parentMobile: '9000000001',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    date: '2026-02-10',
    visitType: 'PHYSICAL_OPD',
    heightCm: 74.0,
    weightKg: 9.3,
    temperatureF: 98.6,
    pulseRate: 118,
    pediatricBmi: 17.0,
    growthStatus: 'HEALTHY',
    chiefComplaints: ['Infantile colic crying in evening', 'Excessive drooling, teething'],
    clinicalObservations: 'Anterior fontanelle flat, soft. Lower central incisors erupting. Abdomen soft, mild gas.',
    diagnosis: 'Infantile Colic & Teething Discomfort',
    doctorNotes: 'CMPA allergy noted. Advised burping technique after every feed and silicone teether.',
    followUpDate: '2026-03-10',
    status: 'FINALIZED',
    createdAt: '2026-02-10 10:15:00',
    updatedAt: '2026-02-10 10:15:00',
    prescription: {
      id: 'rx-5',
      encounterId: 'enc-5',
      prescriptionNumber: 'RX-SDCH-2026-000019',
      childId: 'c1-2',
      childPermanentId: 'DM-SDCH-000102',
      childName: 'Diya Kumar',
      childAge: 2,
      childAgeMonths: 11,
      childGender: 'Girl',
      weightKg: 9.3,
      heightCm: 74.0,
      temperatureF: 98.6,
      pulseRate: 118,
      pediatricBmi: 17.0,
      bloodGroup: 'B+',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      doctorRegNo: 'APMC-38492',
      hospitalName: 'Sri Devi Children Hospital',
      branchId: 'kakinada',
      date: '2026-02-10',
      version: 1,
      diagnosis: 'Infantile Colic & Teething Discomfort',
      allergyBannerSnapshot: ["Cow's Milk Protein (CMPA - Eczema & Loose Stools)"],
      items: [
        {
          id: 'rxi-9',
          medicineName: 'Simethicone with Dill Oil Drops (Colicaid)',
          genericName: 'Simethicone + Dill Oil + Fennel Oil',
          form: 'DROPS',
          strength: '15ml',
          dosage: '5 drops',
          frequency: 'THRICE_DAILY',
          timing: 'BEFORE_FOOD',
          durationDays: 7,
          timeSlots: ['Morning', 'Afternoon', 'Night'],
          instructionEn: 'Give 5 drops 15 minutes before feed when infant is fussy or colicky.',
          instructionTe: 'కడుపుబ్బరం లేదా ఏడుపు ఉన్నప్పుడు పాలు తాగే ముందు 5 చుక్కలు ఇవ్వండి.',
        },
      ],
      specialNotesEn: 'Hold baby upright for 15 minutes after feeding and gentle back patting for burp.',
      specialNotesTe: 'పాలు తాగిన వెంటనే భుజంపై వేసుకుని వీపు నిమరండి.',
      followUpDate: '2026-03-10',
      status: 'FINALIZED',
      createdAt: '2026-02-10 10:15:00',
      updatedAt: '2026-02-10 10:15:00',
    },
  },

  // Encounter 6: Ishaan Kumar (Tonsillopharyngitis - Height less demo)
  {
    id: 'enc-6',
    childId: 'c4-1',
    childPermanentId: 'DM-SDCH-000106',
    childName: 'Ishaan Kumar',
    parentId: 'p4',
    parentName: 'Rajesh Kumar',
    parentMobile: '9000000004',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    date: '2026-06-20',
    visitType: 'PHYSICAL_OPD',
    heightCm: 89.0,
    weightKg: 13.8,
    temperatureF: 100.8,
    pulseRate: 106,
    pediatricBmi: 17.4,
    growthStatus: 'REVIEW_ADVISED',
    chiefComplaints: ['Throat pain with painful swallowing', 'Fever 100.8°F since yesterday'],
    clinicalObservations: 'Bilateral tonsillar hypertrophy with follicular exudates. Cefixime allergy documented.',
    diagnosis: 'Acute Follicular Tonsillopharyngitis',
    doctorNotes: 'Prescribed Azithromycin oral suspension. Discussed low height velocity with father.',
    followUpDate: '2026-06-25',
    status: 'FINALIZED',
    createdAt: '2026-06-20 11:20:00',
    updatedAt: '2026-06-20 11:20:00',
    prescription: {
      id: 'rx-6',
      encounterId: 'enc-6',
      prescriptionNumber: 'RX-SDCH-2026-000067',
      childId: 'c4-1',
      childPermanentId: 'DM-SDCH-000106',
      childName: 'Ishaan Kumar',
      childAge: 4,
      childGender: 'Boy',
      weightKg: 13.8,
      heightCm: 89.0,
      temperatureF: 100.8,
      pulseRate: 106,
      pediatricBmi: 17.4,
      bloodGroup: 'B+',
      doctorId: 'dr-subba-rao',
      doctorName: 'Dr. Subba Rao Vadarevu',
      doctorRegNo: 'APMC-38492',
      hospitalName: 'Sri Devi Children Hospital',
      branchId: 'kakinada',
      date: '2026-06-20',
      version: 1,
      diagnosis: 'Acute Follicular Tonsillopharyngitis',
      allergyBannerSnapshot: ['Cefixime / Cephalosporins (Itchy papular rash)'],
      items: [
        {
          id: 'rxi-10',
          medicineName: 'Azithromycin Oral Suspension (Azee 200mg)',
          genericName: 'Azithromycin 200mg/5ml',
          form: 'SYRUP',
          strength: '200mg/5ml',
          dosage: '3.5 ml',
          frequency: 'ONCE_DAILY',
          timing: 'BEFORE_FOOD',
          durationDays: 5,
          timeSlots: ['Morning'],
          instructionEn: 'Give 3.5 ml once daily 1 hour before breakfast for 5 days.',
          instructionTe: 'ఉదయం అల్పాహారానికి 1 గంట ముందు 3.5 ml ఒకసారి ఇవ్వండి (5 రోజులు).',
        },
        {
          id: 'rxi-11',
          medicineName: 'Paracetamol Suspension (Calpol 250mg)',
          genericName: 'Paracetamol 250mg/5ml',
          form: 'SYRUP',
          strength: '250mg/5ml',
          dosage: '4 ml',
          frequency: 'THRICE_DAILY',
          timing: 'AFTER_FOOD',
          durationDays: 3,
          timeSlots: ['Morning', 'Afternoon', 'Night'],
          instructionEn: 'Give 4 ml for throat pain and fever relief as needed.',
          instructionTe: 'గొంతు నొప్పి లేదా జ్వరం ఉన్నప్పుడు 4 ml ఇవ్వండి.',
        },
      ],
      specialNotesEn: 'Warm salt water gargling twice daily. Drink warm fluids and milk.',
      specialNotesTe: 'గోరువెచ్చని ఉప్పు నీటితో గొంతు పుక్కిలించండి.',
      followUpDate: '2026-06-25',
      status: 'FINALIZED',
      createdAt: '2026-06-20 11:20:00',
      updatedAt: '2026-06-20 11:20:00',
    },
  },
];

const insertEnc = db.prepare(`
  INSERT OR REPLACE INTO encounters (id, appointment_id, child_id, doctor_id, date, data_json)
  VALUES (@id, @appointmentId, @childId, @doctorId, @date, @dataJson)
`);
for (const e of encounters) {
  insertEnc.run({
    id: e.id,
    appointmentId: e.appointmentId || null,
    childId: e.childId,
    doctorId: e.doctorId,
    date: e.date,
    dataJson: JSON.stringify(e),
  });
}

// 6. Update today's appointment queue with various times for live doctor demo
console.log("6. Updating today's live OPD queue across diverse time slots...");
const demoAppointments = [
  // 10:00 AM - Completed Consultation (Aarav Kumar)
  {
    id: 'apt-1',
    appointmentNumber: `SD-K-${ddmmyy}-1000`,
    childId: 'c1-1',
    childName: 'Aarav Kumar',
    parentId: 'p1',
    parentName: 'Ravi Kumar',
    parentMobile: '9000000001',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '10:00',
    expectedConsultationTime: '10:08',
    recommendedArrivalTime: '09:45',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    bookingSource: 'ONLINE',
    heightCm: 104.0,
    weightKg: 16.2,
    temperatureF: 98.6,
    pulseRate: 98,
    pediatricBmi: 15.0,
    actualArrivalTime: '09:44',
    consultationStartTime: '10:08',
    consultationEndTime: '10:22',
    consultationDurationMinutes: 14,
    createdAt: `${today} 08:00:00`,
    updatedAt: `${today} 10:22:00`,
  },

  // 10:15 AM - Currently With Doctor (Vihaan Babu - Peanuts & Sulfa Allergy)
  {
    id: 'apt-2',
    appointmentNumber: `SD-K-${ddmmyy}-1015`,
    childId: 'c2-1',
    childName: 'Vihaan Babu',
    parentId: 'p2',
    parentName: 'Suresh Babu',
    parentMobile: '9000000002',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '10:15',
    expectedConsultationTime: '10:23',
    recommendedArrivalTime: '10:00',
    status: 'WITH_DOCTOR',
    paymentStatus: 'PAID',
    paymentMethod: 'PHONEPE',
    bookingSource: 'ONLINE',
    heightCm: 87.0,
    weightKg: 12.0,
    temperatureF: 100.2,
    pulseRate: 110,
    pediatricBmi: 15.9,
    actualArrivalTime: '10:10',
    consultationStartTime: '10:23',
    createdAt: `${today} 08:15:00`,
    updatedAt: `${today} 10:23:00`,
  },

  // 10:30 AM - Arrived & Waiting (Ananya Devi - Asthma & Egg Allergy)
  {
    id: 'apt-3',
    appointmentNumber: `SD-K-${ddmmyy}-1030`,
    childId: 'c3-1',
    childName: 'Ananya Devi',
    parentId: 'p3',
    parentName: 'Lakshmi Devi',
    parentMobile: '9000000003',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '10:30',
    expectedConsultationTime: '10:38',
    recommendedArrivalTime: '10:15',
    status: 'WAITING',
    paymentStatus: 'PAID',
    paymentMethod: 'PHONEPE',
    bookingSource: 'ONLINE',
    heightCm: 108.0,
    weightKg: 18.0,
    temperatureF: 98.4,
    pulseRate: 94,
    pediatricBmi: 15.4,
    actualArrivalTime: '10:12',
    positionInQueue: 1,
    childrenAhead: 0,
    createdAt: `${today} 08:30:00`,
    updatedAt: `${today} 10:12:00`,
  },

  // 10:45 AM - Arrived & Waiting (Ishaan Kumar - Cefixime Allergy & Height less)
  {
    id: 'apt-4',
    appointmentNumber: `SD-K-${ddmmyy}-1045`,
    childId: 'c4-1',
    childName: 'Ishaan Kumar',
    parentId: 'p4',
    parentName: 'Rajesh Kumar',
    parentMobile: '9000000004',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '10:45',
    expectedConsultationTime: '10:52',
    recommendedArrivalTime: '10:30',
    status: 'ARRIVED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    bookingSource: 'WALK_IN',
    heightCm: 89.5,
    weightKg: 13.9,
    temperatureF: 99.0,
    pulseRate: 98,
    pediatricBmi: 17.3,
    actualArrivalTime: '10:28',
    positionInQueue: 2,
    childrenAhead: 1,
    createdAt: `${today} 08:45:00`,
    updatedAt: `${today} 10:28:00`,
  },

  // 11:00 AM - Approaching (Myra Rao - Eczema & Dust Allergy)
  {
    id: 'apt-5',
    appointmentNumber: `SD-K-${ddmmyy}-1100`,
    childId: 'c5-1',
    childName: 'Myra Rao',
    parentId: 'p5',
    parentName: 'Priya Rao',
    parentMobile: '9000000005',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '11:00',
    expectedConsultationTime: '11:08',
    recommendedArrivalTime: '10:45',
    status: 'APPROACHING',
    paymentStatus: 'PENDING',
    bookingSource: 'ONLINE',
    positionInQueue: 3,
    childrenAhead: 2,
    createdAt: `${today} 09:00:00`,
    updatedAt: `${today} 10:15:00`,
  },

  // 11:15 AM - Booked (Arjun - G6PD Deficiency)
  {
    id: 'apt-6',
    appointmentNumber: `SD-K-${ddmmyy}-1115`,
    childId: 'c6-1',
    childName: 'Arjun',
    parentId: 'p6',
    parentName: 'Mahesh',
    parentMobile: '9000000006',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '11:15',
    expectedConsultationTime: '11:22',
    recommendedArrivalTime: '11:00',
    status: 'BOOKED',
    paymentStatus: 'PENDING',
    bookingSource: 'RECEPTION_PHONE',
    positionInQueue: 4,
    childrenAhead: 3,
    createdAt: `${today} 09:10:00`,
    updatedAt: `${today} 10:15:00`,
  },

  // 11:30 AM - Booked (Kavya - NSAID Allergy & Low Weight)
  {
    id: 'apt-7',
    appointmentNumber: `SD-K-${ddmmyy}-1130`,
    childId: 'c7-1',
    childName: 'Kavya',
    parentId: 'p7',
    parentName: 'Sravani',
    parentMobile: '9000000007',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '11:30',
    expectedConsultationTime: '11:38',
    recommendedArrivalTime: '11:15',
    status: 'BOOKED',
    paymentStatus: 'PENDING',
    bookingSource: 'ONLINE',
    positionInQueue: 5,
    childrenAhead: 4,
    createdAt: `${today} 09:15:00`,
    updatedAt: `${today} 10:15:00`,
  },

  // 11:45 AM - Booked (Diya Kumar - 10 Months Infant with CMPA Allergy)
  {
    id: 'apt-8',
    appointmentNumber: `SD-K-${ddmmyy}-1145`,
    childId: 'c1-2',
    childName: 'Diya Kumar',
    parentId: 'p1',
    parentName: 'Ravi Kumar',
    parentMobile: '9000000001',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '11:45',
    expectedConsultationTime: '11:52',
    recommendedArrivalTime: '11:30',
    status: 'BOOKED',
    paymentStatus: 'PENDING',
    bookingSource: 'ONLINE',
    positionInQueue: 6,
    childrenAhead: 5,
    createdAt: `${today} 09:20:00`,
    updatedAt: `${today} 10:15:00`,
  },

  // 04:30 PM - Afternoon OPD Booked (Anika)
  {
    id: 'apt-9',
    appointmentNumber: `SD-K-${ddmmyy}-1630`,
    childId: 'c10-1',
    childName: 'Anika',
    parentId: 'p10',
    parentName: 'Praveen',
    parentMobile: '9000000010',
    doctorId: 'dr-subba-rao',
    doctorName: 'Dr. Subba Rao Vadarevu',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '16:30',
    expectedConsultationTime: '16:30',
    recommendedArrivalTime: '16:15',
    status: 'BOOKED',
    paymentStatus: 'PENDING',
    bookingSource: 'ONLINE',
    positionInQueue: 1,
    childrenAhead: 0,
    createdAt: `${today} 09:30:00`,
    updatedAt: `${today} 10:15:00`,
  },

  // Dr. Prashant's Queue (Kakinada)
  {
    id: 'apt-p1',
    appointmentNumber: `SD-K-${ddmmyy}-P1000`,
    childId: 'c1-2',
    childName: 'Diya Kumar',
    parentId: 'p1',
    parentName: 'Ravi Kumar',
    parentMobile: '9000000001',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '10:00',
    expectedConsultationTime: '10:00',
    recommendedArrivalTime: '09:45',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    paymentMethod: 'PHONEPE',
    bookingSource: 'ONLINE',
    heightCm: 75.0,
    weightKg: 9.6,
    actualArrivalTime: '09:45',
    consultationStartTime: '10:00',
    consultationEndTime: '10:14',
    consultationDurationMinutes: 14,
    createdAt: `${today} 08:00:00`,
    updatedAt: `${today} 10:14:00`,
  },
  {
    id: 'apt-p2',
    appointmentNumber: `SD-K-${ddmmyy}-P1030`,
    childId: 'c4-1',
    childName: 'Ishaan Kumar',
    parentId: 'p4',
    parentName: 'Rajesh Kumar',
    parentMobile: '9000000004',
    doctorId: 'dr-prashant',
    doctorName: 'Dr. Prashant',
    branchId: 'kakinada',
    branchName: 'Sri Devi Children Hospital - Kakinada',
    date: today,
    bookedTime: '10:30',
    expectedConsultationTime: '10:30',
    recommendedArrivalTime: '10:15',
    status: 'WAITING',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    bookingSource: 'ONLINE',
    heightCm: 89.5,
    weightKg: 13.9,
    actualArrivalTime: '10:15',
    positionInQueue: 1,
    childrenAhead: 0,
    createdAt: `${today} 08:30:00`,
    updatedAt: `${today} 10:15:00`,
  },
];

const insertAppt = db.prepare(`
  INSERT OR REPLACE INTO appointments (
    id, appointment_number, child_id, child_name, parent_id, parent_name, parent_mobile,
    doctor_id, doctor_name, branch_id, branch_name, date, booked_time,
    expected_consultation_time, recommended_arrival_time, status, payment_status, payment_method,
    booking_source, advance_notice_preference_minutes, is_emergency, emergency_reason,
    actual_arrival_time, consultation_start_time, consultation_end_time,
    consultation_duration_minutes, delay_explanation, rescheduled_from_appointment_id,
    position_in_queue, children_ahead, history_json, created_at, updated_at
  ) VALUES (
    @id, @appointmentNumber, @childId, @childName, @parentId, @parentName, @parentMobile,
    @doctorId, @doctorName, @branchId, @branchName, @date, @bookedTime,
    @expectedConsultationTime, @recommendedArrivalTime, @status, @paymentStatus, @paymentMethod,
    @bookingSource, @advanceNoticePreferenceMinutes, @isEmergency, @emergencyReason,
    @actualArrivalTime, @consultationStartTime, @consultationEndTime,
    @consultationDurationMinutes, @delayExplanation, @rescheduledFromAppointmentId,
    @positionInQueue, @childrenAhead, @historyJson, @createdAt, @updatedAt
  )
`);

for (const a of demoAppointments) {
  insertAppt.run({
    id: a.id,
    appointmentNumber: a.appointmentNumber,
    childId: a.childId,
    childName: a.childName,
    parentId: a.parentId,
    parentName: a.parentName,
    parentMobile: a.parentMobile,
    doctorId: a.doctorId,
    doctorName: a.doctorName,
    branchId: a.branchId,
    branchName: a.branchName,
    date: a.date,
    bookedTime: a.bookedTime,
    expectedConsultationTime: a.expectedConsultationTime,
    recommendedArrivalTime: a.recommendedArrivalTime,
    status: a.status,
    paymentStatus: a.paymentStatus,
    paymentMethod: a.paymentMethod || null,
    bookingSource: a.bookingSource,
    advanceNoticePreferenceMinutes: 30,
    isEmergency: 0,
    emergencyReason: null,
    actualArrivalTime: a.actualArrivalTime || null,
    consultationStartTime: a.consultationStartTime || null,
    consultationEndTime: a.consultationEndTime || null,
    consultationDurationMinutes: a.consultationDurationMinutes ?? null,
    delayExplanation: null,
    rescheduledFromAppointmentId: null,
    positionInQueue: a.positionInQueue ?? null,
    childrenAhead: a.childrenAhead ?? null,
    historyJson: '[]',
    createdAt: a.createdAt,
    updatedAt: a.updatedAt,
  });
}

console.log('✅ Demo data successfully seeded into SQLite database!');
console.log('Total Appointments in queue:', db.prepare('SELECT COUNT(*) as count FROM appointments').get().count);
console.log('Total Allergies:', db.prepare('SELECT COUNT(*) as count FROM child_allergies').get().count);
console.log('Total Conditions:', db.prepare('SELECT COUNT(*) as count FROM child_conditions').get().count);
console.log('Total Past Encounters:', db.prepare('SELECT COUNT(*) as count FROM encounters').get().count);
console.log('Total Growth Records:', db.prepare('SELECT COUNT(*) as count FROM pediatric_growth_records').get().count);
